# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xA5f4EDE0C73971BEBcc49E587B59d5c83e9192b9"
    chainName: mantra
    collateralAddressOrDenom: "0xd2b95283011E47257917770D28Bb3EE44c849f6F"
    decimals: 6
    name: MANTRA USD
    standard: EvmHypMultiCollateral
    symbol: mantraUSD
