tokens:
  - chainName: mantra
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: mantraUSD
    name: MANTRA USD
    addressOrDenom: "0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895"
    collateralAddressOrDenom: "0xd2b95283011E47257917770D28Bb3EE44c849f6F"
    connections: []
