# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000014"
    chainName: celestia
    # no info on coingecko for this token yet but will assume its usdc priced
    coinGeckoId: usd-coin
    collateralAddressOrDenom: hyperlane/0x726f757465725f61707000000000000000000000000000020000000000000013
    connections:
      - token: ethereum|eden|0xF4e644772b17b6c57327F4D111a73D68C8cC731B
    decimals: 18
    logoURI: /deployments/warp_routes/eUSD/logo.svg
    name: eUSD
    standard: CosmosNativeHypCollateral
    symbol: eUSD
  - addressOrDenom: "0xF4e644772b17b6c57327F4D111a73D68C8cC731B"
    chainName: eden
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000014
    decimals: 18
    logoURI: /deployments/warp_routes/eUSD/logo.svg
    name: eUSD
    standard: EvmHypSynthetic
    symbol: eUSD
