# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x22eF52C822329E96C3bE0bBB165805603777296C"
    chainName: arbitrum
    collateralAddressOrDenom: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    connections:
      - token: ethereum|ethereum|0x4f7635A2F9795c10DF260C2fc0A23e0F60B4829C
      - token: ethereum|mode|0x01419427C18cC14d66817E90d2e550760230Cf3D
      - token: ethereum|plasma|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
    decimals: 6
    name: USDâ‚®0
    standard: EvmHypCollateral
    symbol: USDTSTAGE
  - addressOrDenom: "0x4f7635A2F9795c10DF260C2fc0A23e0F60B4829C"
    chainName: ethereum
    collateralAddressOrDenom: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    connections:
      - token: ethereum|arbitrum|0x22eF52C822329E96C3bE0bBB165805603777296C
      - token: ethereum|mode|0x01419427C18cC14d66817E90d2e550760230Cf3D
      - token: ethereum|plasma|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
    decimals: 6
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDTSTAGE
  - addressOrDenom: "0x01419427C18cC14d66817E90d2e550760230Cf3D"
    chainName: mode
    connections:
      - token: ethereum|arbitrum|0x22eF52C822329E96C3bE0bBB165805603777296C
      - token: ethereum|ethereum|0x4f7635A2F9795c10DF260C2fc0A23e0F60B4829C
      - token: ethereum|plasma|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
    decimals: 6
    name: Tether USD STAGE
    standard: EvmHypSynthetic
    symbol: USDTSTAGE
  - addressOrDenom: "0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1"
    chainName: plasma
    collateralAddressOrDenom: "0xb8ce59fc3717ada4c02eadf9682a9e934f625ebb"
    connections:
      - token: ethereum|arbitrum|0x22eF52C822329E96C3bE0bBB165805603777296C
      - token: ethereum|ethereum|0x4f7635A2F9795c10DF260C2fc0A23e0F60B4829C
      - token: ethereum|mode|0x01419427C18cC14d66817E90d2e550760230Cf3D
    decimals: 6
    name: USDT0
    standard: EvmHypCollateral
    symbol: USDTSTAGE
