# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x53c0499e7E4aBD3e7994ca161523FD50A12Bb8C8"
    chainName: base
    connections:
      - token: sealevel|solanamainnet|21tAY4poz2VXvghqdSQpn9j7gYravQmGpuQi8pHPx9DS
    decimals: 18
    logoURI: /deployments/warp_routes/TRUMP/logo.png
    name: OFFICIAL TRUMP
    standard: EvmHypSynthetic
    symbol: TRUMP
  - addressOrDenom: "21tAY4poz2VXvghqdSQpn9j7gYravQmGpuQi8pHPx9DS"
    collateralAddressOrDenom: "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN"
    chainName: solanamainnet
    coinGeckoId: official-trump
    connections:
      - token: ethereum|base|0x53c0499e7E4aBD3e7994ca161523FD50A12Bb8C8
    decimals: 6
    logoURI: /deployments/warp_routes/TRUMP/logo.png
    name: OFFICIAL TRUMP
    standard: SealevelHypCollateral
    symbol: TRUMP
