# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
  - addressOrDenom: "0x02EB40D41676F20eDcF95f9110f00412ca53a85F"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
  - addressOrDenom: "0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
  - addressOrDenom: "0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047"
    chainName: bsc
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
  - addressOrDenom: "0xdD313D475f8A9d81CBE2eA953a357f52e10BA357"
    chainName: ethereum
    coinGeckoId: lumia
    collateralAddressOrDenom: "0xD9343a049D5DBd89CD19DC6BcA8c48fB3a0a42a7"
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypCollateral
    symbol: LUMIA
  - addressOrDenom: "0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B"
    chainName: lumiaprism
    coinGeckoId: lumia
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypNative
    symbol: LUMIA
  - addressOrDenom: "0x978B9dE4D8A41b023408383e3B4F760932AaDdc1"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|polygon|0x72749806df5A6BBb72032039bbE9a3f1b17D1936
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
  - addressOrDenom: "0x72749806df5A6BBb72032039bbE9a3f1b17D1936"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0x4e2B1FcC07a8E80736c80Bcf53753e8d0b8042f1
      - token: ethereum|avalanche|0x02EB40D41676F20eDcF95f9110f00412ca53a85F
      - token: ethereum|base|0x155c68274c5C7729c64CF6B0F21f1E6110Fa00d4
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
      - token: ethereum|optimism|0x978B9dE4D8A41b023408383e3B4F760932AaDdc1
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
