# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047"
    chainName: bsc
    connections:
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypSynthetic
    symbol: LUMIA
  - addressOrDenom: "0xdD313D475f8A9d81CBE2eA953a357f52e10BA357"
    chainName: ethereum
    collateralAddressOrDenom: "0xD9343a049D5DBd89CD19DC6BcA8c48fB3a0a42a7"
    connections:
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|lumiaprism|0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypCollateral
    symbol: LUMIA
  - addressOrDenom: "0x98eF2a7DD4261BE8691DCb4B95a08De84d4Ffe5B"
    chainName: lumiaprism
    connections:
      - token: ethereum|bsc|0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047
      - token: ethereum|ethereum|0xdD313D475f8A9d81CBE2eA953a357f52e10BA357
    decimals: 18
    logoURI: /deployments/warp_routes/LUMIA/logo.svg
    name: Lumia Token
    standard: EvmHypNative
    symbol: LUMIA
