# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: CjP8N5L2KV4iWobXoVV1dhftRdfQ7S3rKVrT7Lja9Jku
    chainName: solanamainnet
    coinGeckoId: gigachad-2
    collateralAddressOrDenom: 63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9
    connections:
      - token: sealevel|soon|GHcg7qY2cXQ4Ej9xQqjnLdYUV41bt2ncaPuo5AxN5eTy
    decimals: 5
    logoURI: /deployments/warp_routes/GIGA/logo.svg
    name: GIGACHAD
    standard: SealevelHypCollateral
    symbol: GIGA
  - addressOrDenom: GHcg7qY2cXQ4Ej9xQqjnLdYUV41bt2ncaPuo5AxN5eTy
    chainName: soon
    collateralAddressOrDenom: 5msdLukGrv3nkRH8Nwz6LELahbMB5yzmaM6xGhUfcysm
    connections:
      - token: sealevel|solanamainnet|CjP8N5L2KV4iWobXoVV1dhftRdfQ7S3rKVrT7Lja9Jku
    decimals: 5
    logoURI: /deployments/warp_routes/GIGA/logo.svg
    name: GIGACHAD
    standard: SealevelHypSynthetic
    symbol: GIGA
