# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x261a172eB72D8D32837D123E8AcC4d2e44117195"
    chainName: ethereum
    coinGeckoId: solaxy
    collateralAddressOrDenom: "0xe0B7AD7F8F26e2b00C8b47b5Df370f15F90fCF48"
    connections:
      - token: sealevel|solanamainnet|DaF4pYDy5d6mhwEcMrenpNAjx1gfA9BgcYruUYTsZibE
      - token: sealevel|solaxy|7HZ5A89rQyd3gpSLCFCsAzpap4SZJx3eC2AUMXKJBnfh
    decimals: 18
    logoURI: /deployments/warp_routes/SOLX/logo.png
    name: Solaxy
    standard: EvmHypCollateral
    symbol: SOLX
  - addressOrDenom: DaF4pYDy5d6mhwEcMrenpNAjx1gfA9BgcYruUYTsZibE
    chainName: solanamainnet
    collateralAddressOrDenom: Cf2LnRpmcUxY8qkAyiaaPpgAtUHgzkH3tPhMAevE9zLg
    connections:
      - token: ethereum|ethereum|0x261a172eB72D8D32837D123E8AcC4d2e44117195
      - token: sealevel|solaxy|7HZ5A89rQyd3gpSLCFCsAzpap4SZJx3eC2AUMXKJBnfh
    decimals: 6
    logoURI: /deployments/warp_routes/SOLX/logo.png
    name: Solaxy
    standard: SealevelHypSynthetic
    symbol: SOLX
  - addressOrDenom: 7HZ5A89rQyd3gpSLCFCsAzpap4SZJx3eC2AUMXKJBnfh
    chainName: solaxy
    coinGeckoId: solaxy
    connections:
      - token: ethereum|ethereum|0x261a172eB72D8D32837D123E8AcC4d2e44117195
      - token: sealevel|solanamainnet|DaF4pYDy5d6mhwEcMrenpNAjx1gfA9BgcYruUYTsZibE
    decimals: 6
    logoURI: /deployments/warp_routes/SOLX/logo.png
    name: Solaxy
    standard: SealevelHypNative
    symbol: SOLX
