tokens:
  - aleo:
      addressOrDenom: "hyp_warp_token_usdc.aleo/aleo1txwxlgnmnvwualftnewhf8nyxhv5544dn0uaj9er0ktmx3ysvg9qcld8mx"
      chainName: aleo
      coinGeckoId: usd-coin
      decimals: 6
      logoURI: /deployments/warp_routes/USDC/logo.svg
      name: USD Coin
      standard: AleoHypSynthetic
      symbol: USDC
