# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x8b4192B9Ad1fCa440A5808641261e5289e6de95D"
    chainName: ethereum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|ancient8|0x97423A68BAe94b5De52d767a17aBCc54c157c0E5
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x97423A68BAe94b5De52d767a17aBCc54c157c0E5"
    chainName: ancient8
    connections:
      - token: ethereum|ethereum|0x8b4192B9Ad1fCa440A5808641261e5289e6de95D
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
