# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: arbitrumsepolia
    collateralAddressOrDenom: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
    connections:
      - token: ethereum|modetestnet|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|optimismsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|sepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: modetestnet
    connections:
      - token: ethereum|arbitrumsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|optimismsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|sepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: optimismsepolia
    collateralAddressOrDenom: "0x5fd84259d66Cd46123540766Be93DFE6D43130D7"
    connections:
      - token: ethereum|arbitrumsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|modetestnet|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|sepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: ethereum|arbitrumsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|modetestnet|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
      - token: ethereum|optimismsepolia|0x044ddfd0E99Afd3f2d185935F24da6ab8C82f760
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
