# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xf87697a3B974d1AFc9bd62089D2D16C3EA7474Be"
    chainName: arbitrum
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|base|0xa6826c7Dd74c4e1B400AEF4a362692f99872F5F5
      - token: ethereum|optimism|0x94930Cbfed2483b69DfBed9d96a9CdD7c27D1393
      - token: ethereum|polygon|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|zeronetwork|0x22B34c418e9bB1E640fBef3ADE9de35B643D9237
      - token: ethereum|ethereum|0x88dD52E3576b82571347F62A98D5334fF31dC5Ee
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xa6826c7Dd74c4e1B400AEF4a362692f99872F5F5"
    chainName: base
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0xf87697a3B974d1AFc9bd62089D2D16C3EA7474Be
      - token: ethereum|optimism|0x94930Cbfed2483b69DfBed9d96a9CdD7c27D1393
      - token: ethereum|polygon|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|zeronetwork|0x22B34c418e9bB1E640fBef3ADE9de35B643D9237
      - token: ethereum|ethereum|0x88dD52E3576b82571347F62A98D5334fF31dC5Ee
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x94930Cbfed2483b69DfBed9d96a9CdD7c27D1393"
    chainName: optimism
    collateralAddressOrDenom: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
    connections:
      - token: ethereum|arbitrum|0xf87697a3B974d1AFc9bd62089D2D16C3EA7474Be
      - token: ethereum|base|0xa6826c7Dd74c4e1B400AEF4a362692f99872F5F5
      - token: ethereum|polygon|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|zeronetwork|0x22B34c418e9bB1E640fBef3ADE9de35B643D9237
      - token: ethereum|ethereum|0x88dD52E3576b82571347F62A98D5334fF31dC5Ee
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec"
    chainName: polygon
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    connections:
      - token: ethereum|arbitrum|0xf87697a3B974d1AFc9bd62089D2D16C3EA7474Be
      - token: ethereum|base|0xa6826c7Dd74c4e1B400AEF4a362692f99872F5F5
      - token: ethereum|optimism|0x94930Cbfed2483b69DfBed9d96a9CdD7c27D1393
      - token: ethereum|zeronetwork|0x22B34c418e9bB1E640fBef3ADE9de35B643D9237
      - token: ethereum|ethereum|0x88dD52E3576b82571347F62A98D5334fF31dC5Ee
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x22B34c418e9bB1E640fBef3ADE9de35B643D9237"
    chainName: zeronetwork
    collateralAddressOrDenom: "0x6a6394F47DD0BAF794808F2749C09bd4Ee874E70"
    connections:
      - token: ethereum|arbitrum|0xf87697a3B974d1AFc9bd62089D2D16C3EA7474Be
      - token: ethereum|base|0xa6826c7Dd74c4e1B400AEF4a362692f99872F5F5
      - token: ethereum|optimism|0x94930Cbfed2483b69DfBed9d96a9CdD7c27D1393
      - token: ethereum|polygon|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|ethereum|0x88dD52E3576b82571347F62A98D5334fF31dC5Ee
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x88dD52E3576b82571347F62A98D5334fF31dC5Ee"
    chainName: ethereum
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|arbitrum|0xf87697a3B974d1AFc9bd62089D2D16C3EA7474Be
      - token: ethereum|base|0xa6826c7Dd74c4e1B400AEF4a362692f99872F5F5
      - token: ethereum|optimism|0x94930Cbfed2483b69DfBed9d96a9CdD7c27D1393
      - token: ethereum|polygon|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|zeronetwork|0x22B34c418e9bB1E640fBef3ADE9de35B643D9237
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
