# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb"
    chainName: arbitrum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xb0f76604b7bD094C16CD4A11ce35078FB601fd67"
    chainName: avalanche
    collateralAddressOrDenom: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x37e637891A558B5b621723cbf8Fc771525f280C1"
    chainName: base
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
    chainName: eclipsemainnet
    collateralAddressOrDenom: AKEWE7Bgh87GPp171b4cJPSSZfmZwQ3KaqYqXoKLNAEE
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: SealevelHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xe1De9910fe71cC216490AC7FCF019e13a34481D7"
    chainName: ethereum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734"
    chainName: hyperevm
    collateralAddressOrDenom: "0xb88339CB7199b77E23DB6E890353E22632Ba630f"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x07097C8D351BE0435c60C50B5019c191C18E4EFc"
    chainName: ink
    collateralAddressOrDenom: "0x2D270e6886d130D724215A266106e6832161EAEd"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35"
    chainName: linea
    collateralAddressOrDenom: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16"
    chainName: monad
    collateralAddressOrDenom: "0x754704Bc059F8C67012fEd69BC8A327a5aafb603"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb"
    chainName: optimism
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6"
    chainName: polygon
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: 3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    chainName: solanamainnet
    coinGeckoId: usd-coin
    collateralAddressOrDenom: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: SealevelHypCollateral
    symbol: USDC
  - addressOrDenom: "0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1"
    chainName: unichain
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|worldchain|0x4Da5DE3473196AecCF997311664249C2f92d0e11
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x4Da5DE3473196AecCF997311664249C2f92d0e11"
    chainName: worldchain
    collateralAddressOrDenom: "0x79A02482A880bCE3F13e09Da970dC34db4CD24d1"
    connections:
      - token: ethereum|arbitrum|0xAd4350Ee0f9f5b85BaB115425426086Ae8384ebb
      - token: ethereum|avalanche|0xb0f76604b7bD094C16CD4A11ce35078FB601fd67
      - token: ethereum|base|0x37e637891A558B5b621723cbf8Fc771525f280C1
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: ethereum|hyperevm|0xBF754E7CAF1A6d2dc8E2E02B23466C2643E49734
      - token: ethereum|ink|0x07097C8D351BE0435c60C50B5019c191C18E4EFc
      - token: ethereum|linea|0xb8630B7112BB7c9D6751B8c958e2bE563baCbF35
      - token: ethereum|monad|0x78C31ae2F5E48f4f7ABb0E2E745E8Ce10ea36b16
      - token: ethereum|optimism|0x02bFd67829317D666dc7dFA030F18eaCC12c2cfb
      - token: ethereum|polygon|0xCb9F833f4d6D9Bb9767CDb25c487DA54D67731D6
      - token: ethereum|unichain|0xa7E4dC4078bAc6e97Eec52a4F7642fF51cbb17C1
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
