# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x626B0a3FeA51603350a07b0BED09C871f2047344"
    chainName: arbitrum
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|base|0x7701375eB04688B6dE9f5aD6baC4484B5AE7d89f
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x7701375eB04688B6dE9f5aD6baC4484B5AE7d89f"
    chainName: base
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0x626B0a3FeA51603350a07b0BED09C871f2047344
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
    chainName: eclipsemainnet
    collateralAddressOrDenom: AKEWE7Bgh87GPp171b4cJPSSZfmZwQ3KaqYqXoKLNAEE
    connections:
      - token: ethereum|ethereum|0xe1De9910fe71cC216490AC7FCF019e13a34481D7
      - token: sealevel|solanamainnet|3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: SealevelHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xe1De9910fe71cC216490AC7FCF019e13a34481D7"
    chainName: ethereum
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|arbitrum|0x626B0a3FeA51603350a07b0BED09C871f2047344
      - token: ethereum|base|0x7701375eB04688B6dE9f5aD6baC4484B5AE7d89f
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: 3EpVCPUgyjq2MfGeCttyey6bs5zya5wjYZ2BE6yDg6bm
    chainName: solanamainnet
    coinGeckoId: usd-coin
    collateralAddressOrDenom: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    connections:
      - token: sealevel|eclipsemainnet|EqRSt9aUDMKYKhzd1DGMderr3KNp29VZH3x5P7LFTC8m
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: SealevelHypCollateral
    symbol: USDC
