# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xED56728fb977b0bBdacf65bCdD5e17Bb7e84504f"
    chainName: ethereum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
    connections:
      - token: ethereum|inevm|0x8358d8291e3bedb04804975eea0fe9fe0fafb147
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8358d8291e3bedb04804975eea0fe9fe0fafb147"
    chainName: inevm
    connections:
      - token: ethereum|ethereum|0xED56728fb977b0bBdacf65bCdD5e17Bb7e84504f
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
