# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xbdE0801a78f9c4BC360C34aaf98043EA0cdF4fB0"
    chainName: ethereum
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|krown|0xa3D9cfa4220d6a5ba7b9067D33ebEdbF2DE6F1CF
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xa3D9cfa4220d6a5ba7b9067D33ebEdbF2DE6F1CF"
    chainName: krown
    connections: [] # temporarily deposit-only to krown
    # - token: ethereum|ethereum|0xbdE0801a78f9c4BC360C34aaf98043EA0cdF4fB0
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
