# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xd57c6B54f198bf039C93a821C6c0151C9Ea546ac"
    chainName: arbitrum
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|base|0x1547B13bD71126D92e93092cAD07807eEDb6Fc26
      - token: ethereum|ethereum|0x066abc14c59cF7681b4b66844500733D2258032A
      - token: ethereum|lumiaprism|0x2D0b95BB7eC6A8A3B3229e8FB8bE5848aBEA137a
      - token: ethereum|optimism|0xD6880E571A11FBd14Fa63a9e18A8152cAB3Bb720
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x1547B13bD71126D92e93092cAD07807eEDb6Fc26"
    chainName: base
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0xd57c6B54f198bf039C93a821C6c0151C9Ea546ac
      - token: ethereum|ethereum|0x066abc14c59cF7681b4b66844500733D2258032A
      - token: ethereum|lumiaprism|0x2D0b95BB7eC6A8A3B3229e8FB8bE5848aBEA137a
      - token: ethereum|optimism|0xD6880E571A11FBd14Fa63a9e18A8152cAB3Bb720
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x066abc14c59cF7681b4b66844500733D2258032A"
    chainName: ethereum
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|arbitrum|0xd57c6B54f198bf039C93a821C6c0151C9Ea546ac
      - token: ethereum|base|0x1547B13bD71126D92e93092cAD07807eEDb6Fc26
      - token: ethereum|lumiaprism|0x2D0b95BB7eC6A8A3B3229e8FB8bE5848aBEA137a
      - token: ethereum|optimism|0xD6880E571A11FBd14Fa63a9e18A8152cAB3Bb720
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x2D0b95BB7eC6A8A3B3229e8FB8bE5848aBEA137a"
    chainName: lumiaprism
    collateralAddressOrDenom: "0xFF297AC2CB0a236155605EB37cB55cFCAe6D3F01"
    connections:
      - token: ethereum|arbitrum|0xd57c6B54f198bf039C93a821C6c0151C9Ea546ac
      - token: ethereum|base|0x1547B13bD71126D92e93092cAD07807eEDb6Fc26
      - token: ethereum|ethereum|0x066abc14c59cF7681b4b66844500733D2258032A
      - token: ethereum|optimism|0xD6880E571A11FBd14Fa63a9e18A8152cAB3Bb720
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateralFiat
    symbol: USDC
  - addressOrDenom: "0xD6880E571A11FBd14Fa63a9e18A8152cAB3Bb720"
    chainName: optimism
    collateralAddressOrDenom: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
    connections:
      - token: ethereum|arbitrum|0xd57c6B54f198bf039C93a821C6c0151C9Ea546ac
      - token: ethereum|base|0x1547B13bD71126D92e93092cAD07807eEDb6Fc26
      - token: ethereum|ethereum|0x066abc14c59cF7681b4b66844500733D2258032A
      - token: ethereum|lumiaprism|0x2D0b95BB7eC6A8A3B3229e8FB8bE5848aBEA137a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
