tokens:
  - addressOrDenom: "0xC9d7f943d2056a5927FFCE4b689dA17A9719374C"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6"
    chainName: ink
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: linea
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6"
    chainName: plume
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23"
    chainName: sei
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: sonic
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: unichain
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|worldchain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xc508E179297ef72e65909e4D072758C2d0B92B83"
    chainName: worldchain
    connections:
      - token: ethereum|arbitrum|0xC9d7f943d2056a5927FFCE4b689dA17A9719374C
      - token: ethereum|avalanche|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|base|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|ethereum|0xB92aBe104fCd7AB976987C5B54ea86C4893DaFdA
      - token: ethereum|hyperevm|0xC802a4701de6e6c64A34365Dc7a31CCefE7e3AeC
      - token: ethereum|ink|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|linea|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|optimism|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|plume|0x550C6eD65E0E7B65E7fb72120D37F244E6E005B6
      - token: ethereum|polygon|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|sei|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|sonic|0xc508E179297ef72e65909e4D072758C2d0B92B83
      - token: ethereum|unichain|0xc508E179297ef72e65909e4D072758C2d0B92B83
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
