tokens:
  - addressOrDenom: "0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8dadbDE67eD0589d90cdE3C940045F10092AcC11"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xfd8Caf26711A49f77007989307b75667f12454f6"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x9cf82eABff9cd37850f4547316Ee2016f316bb52"
    chainName: ink
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8dadbDE67eD0589d90cdE3C940045F10092AcC11"
    chainName: linea
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf"
    chainName: plume
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8dadbDE67eD0589d90cdE3C940045F10092AcC11"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B"
    chainName: sei
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8dadbDE67eD0589d90cdE3C940045F10092AcC11"
    chainName: sonic
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B"
    chainName: unichain
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|worldchain|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8dadbDE67eD0589d90cdE3C940045F10092AcC11"
    chainName: worldchain
    connections:
      - token: ethereum|arbitrum|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|avalanche|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|base|0x584244d02b0fBf9054A5D5C9e9cE9A2E8adA0e28
      - token: ethereum|ethereum|0xEE4a09db2C25592C04b8b342CB89f9a7f5E20BD2
      - token: ethereum|hyperevm|0xfd8Caf26711A49f77007989307b75667f12454f6
      - token: ethereum|ink|0x9cf82eABff9cd37850f4547316Ee2016f316bb52
      - token: ethereum|linea|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|optimism|0xb0B8D4C6EF212D76d5079df5Ff7A0888A27e9b32
      - token: ethereum|plume|0x0706DE5b87F03C0c6fDC8a03D987D06f776eF6bf
      - token: ethereum|polygon|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|sei|0xAE3d8F7C4d7527BfaF2f15c43D1B6ea39802838B
      - token: ethereum|sonic|0x8dadbDE67eD0589d90cdE3C940045F10092AcC11
      - token: ethereum|unichain|0x5b7A1a03F26C05D68ada7CE67d49db263e2D0d9B
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
