# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x238365F7D5686e88BAc6333581A9Dd98421f14F6"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2"
    chainName: ink
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x992B13e17997c6c182545B5C4f2bf2C453C41855"
    chainName: linea
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xDf347f7602fFF536337c0B90cEC19CD6998427C4"
    chainName: plume
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac"
    chainName: sei
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xF32F45fB4315841F93289A1ECD62efD89F9964C9"
    chainName: sonic
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xe4326C1618A424680ec4705268A48EC4031e9B72"
    chainName: unichain
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|worldchain|0x521004D2c87f5129193B35f61fADC7ea1B937550
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x521004D2c87f5129193B35f61fADC7ea1B937550"
    chainName: worldchain
    connections:
      - token: ethereum|arbitrum|0xaCb73C92040e3B5421f63798713e9eE1CcE5d9c5
      - token: ethereum|avalanche|0x238365F7D5686e88BAc6333581A9Dd98421f14F6
      - token: ethereum|base|0xa2EdB3d3096C390fFE932CD13d1eE5B10683C3d5
      - token: ethereum|ethereum|0x3cF84d98DcAe3515AC3afa066a4E2F38F85Ff1c7
      - token: ethereum|hyperevm|0x9Fc6f76A877280EaA2c11e0B73F4e3b86D293693
      - token: ethereum|ink|0xFcb75bD4Beea2BFD60aF352B5E7eE0e2B75F6dA2
      - token: ethereum|linea|0x992B13e17997c6c182545B5C4f2bf2C453C41855
      - token: ethereum|optimism|0x76E88eEE5Ba22498c18356fa63F52DBe5aBEdE6d
      - token: ethereum|plume|0xDf347f7602fFF536337c0B90cEC19CD6998427C4
      - token: ethereum|polygon|0x5Abf8457206b37c40f10A924eF6bcbF9BA8301a7
      - token: ethereum|sei|0xb7D5208E9820647b9Bb0e132336F550D84Ab79Ac
      - token: ethereum|sonic|0xF32F45fB4315841F93289A1ECD62efD89F9964C9
      - token: ethereum|unichain|0xe4326C1618A424680ec4705268A48EC4031e9B72
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
