tokens:
  - addressOrDenom: "0x4c19c653a8419A475d9B6735511cB81C15b8d9b2"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7"
    chainName: ink
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: linea
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7"
    chainName: plume
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6"
    chainName: sei
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: sonic
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: unichain
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|worldchain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x33e94B6D2ae697c16a750dB7c3d9443622C4405a"
    chainName: worldchain
    connections:
      - token: ethereum|arbitrum|0x4c19c653a8419A475d9B6735511cB81C15b8d9b2
      - token: ethereum|avalanche|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|base|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|ethereum|0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23
      - token: ethereum|hyperevm|0xDdf252a063f8c5C399B9ccDBbaDBA55225F53Da1
      - token: ethereum|ink|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|linea|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|optimism|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|plume|0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7
      - token: ethereum|polygon|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|sei|0x346961e35b9a2ea5511AA5FC44DBF61Ab0f293F6
      - token: ethereum|sonic|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
      - token: ethereum|unichain|0x33e94B6D2ae697c16a750dB7c3d9443622C4405a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
