tokens:
  - addressOrDenom: "0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xCB35d7730843F770625bE36A0E4228c17fDcBC09"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x31169ee5A8C0D680de74461d7B5394fFc7C3576B"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xe10b7b030C75C80359841CB0ec892E233F03f145"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x70CF23d09784fCA62be304c928BCA9F1801B1F21"
    chainName: ink
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA"
    chainName: linea
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x890CB8Dd7b6817b2Ab45b484264386ee48000F21"
    chainName: plume
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599"
    chainName: sei
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x45935ea31cF8fd877122DB8D9c47065Bbc095135"
    chainName: sonic
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xCB35d7730843F770625bE36A0E4228c17fDcBC09"
    chainName: unichain
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|worldchain|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA"
    chainName: worldchain
    connections:
      - token: ethereum|arbitrum|0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f
      - token: ethereum|avalanche|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
      - token: ethereum|base|0x31169ee5A8C0D680de74461d7B5394fFc7C3576B
      - token: ethereum|ethereum|0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07
      - token: ethereum|hyperevm|0xe10b7b030C75C80359841CB0ec892E233F03f145
      - token: ethereum|ink|0x70CF23d09784fCA62be304c928BCA9F1801B1F21
      - token: ethereum|linea|0x89aAa89D36F995b41d929f2D29b8Ee7C9c8e54cA
      - token: ethereum|optimism|0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30
      - token: ethereum|plume|0x890CB8Dd7b6817b2Ab45b484264386ee48000F21
      - token: ethereum|polygon|0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872
      - token: ethereum|sei|0x3Ce3585d2Fa9AfB4101Fd6007b0839ddCb5b9599
      - token: ethereum|sonic|0x45935ea31cF8fd877122DB8D9c47065Bbc095135
      - token: ethereum|unichain|0xCB35d7730843F770625bE36A0E4228c17fDcBC09
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
