# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x493924d775Db32c460E25c303924710C01166BEb"
    chainName: arbitrum
    connections:
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xe68b634c100798002745925DbE834Aa6a3F80328"
    chainName: avalanche
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xa3a457F110a69b62cF141E999313a0dcaf1882dE"
    chainName: hyperevm
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a"
    chainName: ink
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x5d2977772b66233C0F3beAef1B675Ae6Bf240560"
    chainName: linea
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xa64Aad213454956EDb9f2ca2CD3e6753fC702606"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8"
    chainName: plume
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xe03a9B3905929CC18A116207318cE77Ced09D184"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xaA6bff247587623CCe374388Be6601D747e00d15"
    chainName: sei
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x10Ce7D1c7436306718D84af72e6DBD509a222b0B"
    chainName: sonic
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673"
    chainName: unichain
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|worldchain|0x03378A0D997bD6246394Ae3b6A2d0075317Cc236
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0x03378A0D997bD6246394Ae3b6A2d0075317Cc236"
    chainName: worldchain
    connections:
      - token: ethereum|arbitrum|0x493924d775Db32c460E25c303924710C01166BEb
      - token: ethereum|avalanche|0xe68b634c100798002745925DbE834Aa6a3F80328
      - token: ethereum|base|0x08d33dD7A90d8Cd43cD6991f3FE0ab5E175798eF
      - token: ethereum|ethereum|0xabD7C82306035702B253b39C9DB9763cBE1Ad5CB
      - token: ethereum|hyperevm|0xa3a457F110a69b62cF141E999313a0dcaf1882dE
      - token: ethereum|ink|0xfefE8bB5Ac5F30C27E0F74dE3c0bD7936A25391a
      - token: ethereum|linea|0x5d2977772b66233C0F3beAef1B675Ae6Bf240560
      - token: ethereum|optimism|0xa64Aad213454956EDb9f2ca2CD3e6753fC702606
      - token: ethereum|plume|0x37b240604b8aB9EB6D38Cd081147e6C4Aed353E8
      - token: ethereum|polygon|0xe03a9B3905929CC18A116207318cE77Ced09D184
      - token: ethereum|sei|0xaA6bff247587623CCe374388Be6601D747e00d15
      - token: ethereum|sonic|0x10Ce7D1c7436306718D84af72e6DBD509a222b0B
      - token: ethereum|unichain|0x624Fd80a99EbCc2Fa0826e990CBa6d4a12F4c673
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
