tokens:
  - chainName: arbitrum
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0x94C62e7958738B65737a0Db8A5077def3AED84AA"
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections: []
  - chainName: base
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0x73Ef899fDa87213e26501707ab585028BFB297c8"
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections: []
