tokens:
  - chainName: ink
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USDC
    addressOrDenom: "0x2EA98401A0Af88cb44B9666b4C970B7a4f3217B2"
    collateralAddressOrDenom: "0x2D270e6886d130D724215A266106e6832161EAEd"
