# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: BEzLRBDBJyRrzZN2CfGJB3bedBj3HwHqj6MB8BQn1mdL
    chainName: solanamainnet
    coinGeckoId: cat-in-a-dogs-world
    collateralAddressOrDenom: MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5
    connections:
      - token: sealevel|soon|9JcBcd9bRDQjRtkZq7sWfNF4DRFRA24KsuhV9rTemUgC
    decimals: 5
    logoURI: /deployments/warp_routes/MEW/logo.svg
    name: MEW
    standard: SealevelHypCollateral
    symbol: MEW
  - addressOrDenom: 9JcBcd9bRDQjRtkZq7sWfNF4DRFRA24KsuhV9rTemUgC
    chainName: soon
    collateralAddressOrDenom: GvW8my8MggjKf8m3LAds4bpL4GgQRmRaDhbWUon7ZzF3
    connections:
      - token: sealevel|solanamainnet|BEzLRBDBJyRrzZN2CfGJB3bedBj3HwHqj6MB8BQn1mdL
    decimals: 5
    logoURI: /deployments/warp_routes/MEW/logo.svg
    name: MEW
    standard: SealevelHypSynthetic
    symbol: MEW
