# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x306aCd0c07c430AbBBb2e74Ef7bdE94F32A898c0"
    chainName: base
    connections:
      - token: ethereum|ethereum|0x8E1C6992621f1f647C79A297035B5484B9fb6864
    decimals: 18
    logoURI: /deployments/warp_routes/SEDA/logo.svg
    name: SEDA
    standard: EvmHypSynthetic
    symbol: SEDA
  - addressOrDenom: "0x8E1C6992621f1f647C79A297035B5484B9fb6864"
    chainName: ethereum
    coinGeckoId: seda-2
    collateralAddressOrDenom: "0x14862c03A0cACcC1aB328B062E64e31B2a1afcd7"
    connections:
      - token: ethereum|base|0x306aCd0c07c430AbBBb2e74Ef7bdE94F32A898c0
    decimals: 18
    logoURI: /deployments/warp_routes/SEDA/logo.svg
    name: SEDA
    standard: EvmHypCollateral
    symbol: SEDA
