tokens:
  - addressOrDenom: test_hyp_warp_token_eth.aleo/aleo1n6g5lvv7706pmcy2lsfta7k5d7tx522ly50ykr5frneq4pvkugzqqqtjav
    chainName: aleotestnet
    connections:
      - token: ethereum|sepolia|0x7c4aAAaB1f846881af95f5736d127F3F3F07F25F
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: AleoHypSynthetic
    symbol: ETH
  - addressOrDenom: "0x7c4aAAaB1f846881af95f5736d127F3F3F07F25F"
    chainName: sepolia
    connections:
      - token: aleo|aleo|test_hyp_warp_token_eth.aleo/aleo1n6g5lvv7706pmcy2lsfta7k5d7tx522ly50ykr5frneq4pvkugzqqqtjav
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
