# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x19dcF74D21d85Cf82d1a047ef80C64954E4aa009"
    chainName: arbitrum
    coinGeckoId: ethereum
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xE4A9622Bf50025fE99A576D484AEf16280A5304f"
    chainName: base
    coinGeckoId: ethereum
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xE0A5921Bcc37eb2FeCc452AE574b86bD4c332196"
    chainName: ethereum
    coinGeckoId: ethereum
    connections:
      - token: ethereum|lumiaprism|0xdCB5227EA8E5FDE0f761A55dC669EC09807E7C8b
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xdCB5227EA8E5FDE0f761A55dC669EC09807E7C8b"
    chainName: lumiaprism
    connections:
      - token: ethereum|ethereum|0xE0A5921Bcc37eb2FeCc452AE574b86bD4c332196
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypSynthetic
    symbol: WETH
  - addressOrDenom: "0x4e550422D67f208eE25A730D11dCe9201cF3Aa3a"
    chainName: optimism
    coinGeckoId: ethereum
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x56c3AAd2d754b2177dBDa02A4dCb0571486460a9"
    chainName: polygon
    coinGeckoId: ethereum
    collateralAddressOrDenom: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
