# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88"
    chainName: arbitrum
    coinGeckoId: ethereum
    connections:
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x885598858b68562FE5001F8eE022522313257C7a"
    chainName: base
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xA900858116D7605a01AfC7595450d8D78555Bc83"
    chainName: blast
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xFc9F3387eb4385785420f661CE7A9E486f404b8F"
    chainName: bsc
    coinGeckoId: ethereum
    collateralAddressOrDenom: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8"
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
  - addressOrDenom: "0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0"
    chainName: ethereum
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c"
    chainName: gnosis
    coinGeckoId: ethereum
    collateralAddressOrDenom: "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1"
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
  - addressOrDenom: "0xA92D6084709469A2B2339919FfC568b7C5D7888D"
    chainName: mantle
    coinGeckoId: ethereum
    collateralAddressOrDenom: "0xdEAddEaDdeadDEadDEADDEAddEADDEAddead1111"
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
  - addressOrDenom: "0xef043d913b196dc87CB1256850894AA72DAD5933"
    chainName: mode
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539"
    chainName: optimism
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779"
    chainName: polygon
    coinGeckoId: ethereum
    collateralAddressOrDenom: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
  - addressOrDenom: "0xF85379CF296f84871dee84826153d6F5ccA9de3B"
    chainName: scroll
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x2E2c9BeE342398E26156Da12769262087de6EdDC"
    chainName: zeronetwork
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xA900858116D7605a01AfC7595450d8D78555Bc83"
    chainName: zoramainnet
    coinGeckoId: ethereum
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|lisk|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0"
    chainName: lisk
    connections:
      - token: ethereum|arbitrum|0x6B8D1F18819DACA1fB966CF8Cff12feb4c00EB88
      - token: ethereum|base|0x885598858b68562FE5001F8eE022522313257C7a
      - token: ethereum|blast|0xA900858116D7605a01AfC7595450d8D78555Bc83
      - token: ethereum|bsc|0xFc9F3387eb4385785420f661CE7A9E486f404b8F
      - token: ethereum|ethereum|0x85E9ae52B10f35e3D15264F1E906895B1D7Da1a0
      - token: ethereum|gnosis|0x5DBeAEC137d1ef9a240599656073Ae3E717fae3c
      - token: ethereum|mantle|0xA92D6084709469A2B2339919FfC568b7C5D7888D
      - token: ethereum|mode|0xef043d913b196dc87CB1256850894AA72DAD5933
      - token: ethereum|optimism|0x14A77BdAb46bBEb7DAfc3E4cB4732A51241Ef539
      - token: ethereum|polygon|0xda8b55BB3Dc6B74042033f9493A5Bffa3d8EA779
      - token: ethereum|scroll|0xF85379CF296f84871dee84826153d6F5ccA9de3B
      - token: ethereum|zeronetwork|0x2E2c9BeE342398E26156Da12769262087de6EdDC
      - token: ethereum|zoramainnet|0xA900858116D7605a01AfC7595450d8D78555Bc83
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH
