tokens:
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000010"
    chainName: celestia
    coinGeckoId: ethereum
    collateralAddressOrDenom: hyperlane/0x726f757465725f6170700000000000000000000000000002000000000000000b
    connections:
      - token: ethereum|eden|0x23958cBa555AC52C9495Df9b121ff73003e39dBb
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: CosmosNativeHypCollateral
    symbol: ETH
  - addressOrDenom: "0x23958cBa555AC52C9495Df9b121ff73003e39dBb"
    chainName: eden
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000010
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH
