# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x15b5D6B614242B118AA404528A7f3E2Ad241e4A4"
    chainName: ethereum
    coinGeckoId: ethereum
    connections:
      - token: ethereum|viction|0x182e8d7c5f1b06201b102123fc7df0eaeb445a7b
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ethereum
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x182e8d7c5f1b06201b102123fc7df0eaeb445a7b"
    chainName: viction
    connections:
      - token: ethereum|ethereum|0x15b5D6B614242B118AA404528A7f3E2Ad241e4A4
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ethereum
    standard: EvmHypSynthetic
    symbol: ETH
