# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x7Ce0c5B1d9D0FB35f2D7d57DfE21F371c8dd9f14"
    chainName: ethereum
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
