tokens:
  - addressOrDenom: "0x5b4172Eed2886bC3623a9ed9CCC98DBE2832B7d2"
    chainName: arbitrum
    connections:
      - token: ethereum|base|0x94620098a0AF6fBEb3eDd2BC6F52D1aa228e9077
      - token: ethereum|ethereum|0xd17c7E32a2D3BB76234925bee159aC18a43E8322
      - token: ethereum|mode|0x02615459260E5329500d23577e7950098697E203
      - token: ethereum|optimism|0x7B3877CD74c7b7f1fc5ACE40Ad5C5aE1ebC87AA1
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x94620098a0AF6fBEb3eDd2BC6F52D1aa228e9077"
    chainName: base
    connections:
      - token: ethereum|arbitrum|0x5b4172Eed2886bC3623a9ed9CCC98DBE2832B7d2
      - token: ethereum|ethereum|0xd17c7E32a2D3BB76234925bee159aC18a43E8322
      - token: ethereum|mode|0x02615459260E5329500d23577e7950098697E203
      - token: ethereum|optimism|0x7B3877CD74c7b7f1fc5ACE40Ad5C5aE1ebC87AA1
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xd17c7E32a2D3BB76234925bee159aC18a43E8322"
    chainName: ethereum
    connections:
      - token: ethereum|arbitrum|0x5b4172Eed2886bC3623a9ed9CCC98DBE2832B7d2
      - token: ethereum|base|0x94620098a0AF6fBEb3eDd2BC6F52D1aa228e9077
      - token: ethereum|mode|0x02615459260E5329500d23577e7950098697E203
      - token: ethereum|optimism|0x7B3877CD74c7b7f1fc5ACE40Ad5C5aE1ebC87AA1
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x02615459260E5329500d23577e7950098697E203"
    chainName: mode
    connections:
      - token: ethereum|arbitrum|0x5b4172Eed2886bC3623a9ed9CCC98DBE2832B7d2
      - token: ethereum|base|0x94620098a0AF6fBEb3eDd2BC6F52D1aa228e9077
      - token: ethereum|ethereum|0xd17c7E32a2D3BB76234925bee159aC18a43E8322
      - token: ethereum|optimism|0x7B3877CD74c7b7f1fc5ACE40Ad5C5aE1ebC87AA1
    decimals: 18
    name: Ether STAGE
    standard: EvmHypSynthetic
    symbol: ETH
  - addressOrDenom: "0x7B3877CD74c7b7f1fc5ACE40Ad5C5aE1ebC87AA1"
    chainName: optimism
    connections:
      - token: ethereum|arbitrum|0x5b4172Eed2886bC3623a9ed9CCC98DBE2832B7d2
      - token: ethereum|base|0x94620098a0AF6fBEb3eDd2BC6F52D1aa228e9077
      - token: ethereum|ethereum|0xd17c7E32a2D3BB76234925bee159aC18a43E8322
      - token: ethereum|mode|0x02615459260E5329500d23577e7950098697E203
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
