# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC"
    chainName: arbitrum
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x43295D726C09a1578960549f2513E186C3B62e57"
    chainName: avalanche
    collateralAddressOrDenom: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea"
    chainName: base
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: 6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
    chainName: eclipsemainnet
    collateralAddressOrDenom: CFbKuNFUy1gDmu5yb3N49g7BUr6ftAR1f4Sricnh2ABv
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USD Coin STAGE
    standard: SealevelHypSynthetic
    symbol: USDCSTAGE
  - addressOrDenom: "0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5"
    chainName: ethereum
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877"
    chainName: hyperevm
    collateralAddressOrDenom: "0xb88339CB7199b77E23DB6E890353E22632Ba630f"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x416714e092F2b6e3296039ca2adF7eb6e06806F7"
    chainName: ink
    collateralAddressOrDenom: "0x2D270e6886d130D724215A266106e6832161EAEd"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D"
    chainName: linea
    collateralAddressOrDenom: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9"
    chainName: monad
    collateralAddressOrDenom: "0x754704Bc059F8C67012fEd69BC8A327a5aafb603"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE"
    chainName: optimism
    collateralAddressOrDenom: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0xfc78F4Dace2Ee0057281D0267DB3491181510593"
    chainName: polygon
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    chainName: solanamainnet
    collateralAddressOrDenom: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USDCSTAGE
    standard: SealevelHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1"
    chainName: unichain
    collateralAddressOrDenom: "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|worldchain|0x414B67F62b143d6db6E9b633168Dd6fd4DA20642
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    logoURI: /deployments/warp_routes/USDCSTAGE/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDCSTAGE
  - addressOrDenom: "0x414B67F62b143d6db6E9b633168Dd6fd4DA20642"
    chainName: worldchain
    collateralAddressOrDenom: "0x79A02482A880bCE3F13e09Da970dC34db4CD24d1"
    connections:
      - token: ethereum|arbitrum|0x604610E6B3310852f1599a6eDbEbd6b6b2B766DC
      - token: ethereum|avalanche|0x43295D726C09a1578960549f2513E186C3B62e57
      - token: ethereum|base|0x5A0E13290ec57F5e9031D01D03C6A40029Cc24ea
      - token: ethereum|ethereum|0x04C26A1Efb87D5Ac9ee6179754B4CDDC61fC11d5
      - token: ethereum|hyperevm|0xfF806E766f9dD784b370c5A2a4BaaF21Ea62D877
      - token: ethereum|ink|0x416714e092F2b6e3296039ca2adF7eb6e06806F7
      - token: ethereum|linea|0xaA3C7A670f0AFd18c2eC8B998aA56Bb371E0df5D
      - token: ethereum|monad|0x1b681aaccc77B5aeE34675eac5cE3dDeAbc0b4c9
      - token: ethereum|optimism|0x36D930c7782BafE74Ff52CAb54648a1b2ecC48bE
      - token: ethereum|polygon|0xfc78F4Dace2Ee0057281D0267DB3491181510593
      - token: ethereum|unichain|0x33e6681548a0E5A07bf2Ffa33e7Ef274F08a34E1
      - token: sealevel|eclipsemainnet|6QSWUmEaEcE2KJrU5jq7T11tNRaVsgnG8XULezjg7JjL
      - token: sealevel|solanamainnet|E5rVV8zXwtc4TKGypCJvSBaYbgxa4XaYg5MS6N9QGdeo
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDCSTAGE
