# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: J8fVLBiLMniYxaBYhfpGmqDpf2qtgaiDAPuznfRMhLs6
    chainName: solanamainnet
    coinGeckoId: peanut-the-squirrel
    collateralAddressOrDenom: 2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump
    connections:
      - token: sealevel|soon|5WHM6rm9HpFqNY8hye9ZY9vrgCCM7M5YnCeKcq29FpXz
    decimals: 6
    logoURI: /deployments/warp_routes/Pnut/logo.svg
    name: Peanut the Squirrel
    standard: SealevelHypCollateral
    symbol: Pnut
  - addressOrDenom: 5WHM6rm9HpFqNY8hye9ZY9vrgCCM7M5YnCeKcq29FpXz
    chainName: soon
    collateralAddressOrDenom: HHJDLRYkp2SPdo2Wv7F62ccKeqVcgEzowaEctUP2r2Cu
    connections:
      - token: sealevel|solanamainnet|J8fVLBiLMniYxaBYhfpGmqDpf2qtgaiDAPuznfRMhLs6
    decimals: 6
    logoURI: /deployments/warp_routes/Pnut/logo.svg
    name: Peanut the Squirrel
    standard: SealevelHypSynthetic
    symbol: Pnut
