# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: FF6PWPjiY1hwy3Kt5qTDoqhZ3PbmaXKYPzADEjZbK9iN
    chainName: eclipsemainnet
    collateralAddressOrDenom: 97UNrMjduqbHhnZ5T5w3DifYnxwM2LAEpYxfoMcMjXK1
    connections:
      - token: sealevel|solanamainnet|22z73A4E7QjwjTsHGJptnALgBGuovEabCcQtPdBaQPpJ
      - token: sealevel|sonicsvm|BW1QM1PvvU4VFvZYPhgnJSfFR1d49BAGy4X1uDmtTRLw
      - token: sealevel|soon|6trL4uE7KANMqrPT5rw4uiN6TSTw7c5Ssv4GdAkhTzVc
    decimals: 9
    logoURI: /deployments/warp_routes/wfragSOL/logo.svg
    name: Wrapped Fragmetric Restaked SOL
    standard: SealevelHypSynthetic
    symbol: wfragSOL
  - addressOrDenom: 22z73A4E7QjwjTsHGJptnALgBGuovEabCcQtPdBaQPpJ
    chainName: solanamainnet
    coinGeckoId: wrapped-fragsol
    collateralAddressOrDenom: WFRGSWjaz8tbAxsJitmbfRuFV2mSNwy7BMWcCwaA28U
    connections:
      - token: sealevel|eclipsemainnet|FF6PWPjiY1hwy3Kt5qTDoqhZ3PbmaXKYPzADEjZbK9iN
      - token: sealevel|sonicsvm|BW1QM1PvvU4VFvZYPhgnJSfFR1d49BAGy4X1uDmtTRLw
      - token: sealevel|soon|6trL4uE7KANMqrPT5rw4uiN6TSTw7c5Ssv4GdAkhTzVc
    decimals: 9
    logoURI: /deployments/warp_routes/wfragSOL/logo.svg
    name: Wrapped Fragmetric Restaked SOL
    standard: SealevelHypCollateral
    symbol: wfragSOL
  - addressOrDenom: BW1QM1PvvU4VFvZYPhgnJSfFR1d49BAGy4X1uDmtTRLw
    chainName: sonicsvm
    collateralAddressOrDenom: ApsE83FeU6NhRh1xYHiN2JmF2oDecNXZxn5ihXHFNWWL
    connections:
      - token: sealevel|eclipsemainnet|FF6PWPjiY1hwy3Kt5qTDoqhZ3PbmaXKYPzADEjZbK9iN
      - token: sealevel|solanamainnet|22z73A4E7QjwjTsHGJptnALgBGuovEabCcQtPdBaQPpJ
      - token: sealevel|soon|6trL4uE7KANMqrPT5rw4uiN6TSTw7c5Ssv4GdAkhTzVc
    decimals: 9
    logoURI: /deployments/warp_routes/wfragSOL/logo.svg
    name: Wrapped Fragmetric Restaked SOL
    standard: SealevelHypSynthetic
    symbol: wfragSOL
  - addressOrDenom: 6trL4uE7KANMqrPT5rw4uiN6TSTw7c5Ssv4GdAkhTzVc
    chainName: soon
    collateralAddressOrDenom: 7T9sawCGJAV4wC49CjHpw8TGL3ZuPAbZipNq86YXGecy
    connections:
      - token: sealevel|eclipsemainnet|FF6PWPjiY1hwy3Kt5qTDoqhZ3PbmaXKYPzADEjZbK9iN
      - token: sealevel|solanamainnet|22z73A4E7QjwjTsHGJptnALgBGuovEabCcQtPdBaQPpJ
      - token: sealevel|sonicsvm|BW1QM1PvvU4VFvZYPhgnJSfFR1d49BAGy4X1uDmtTRLw
    decimals: 9
    logoURI: /deployments/warp_routes/wfragSOL/logo.svg
    name: Wrapped Fragmetric Restaked SOL
    standard: SealevelHypSynthetic
    symbol: wfragSOL
