# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: 9PHKQFEDzedHuigSm1ZBojEX4DVF3cincGZwy3k7VHTN
    chainName: solanamainnet
    coinGeckoId: solayer-staked-sol
    collateralAddressOrDenom: sSo14endRuUbvQaJS3dq36Q829a3A6BEfoeeRGJywEh
    connections:
      - token: sealevel|sonicsvm|XYbsJQGzZgPDbt9Swd2ao54nhGSq8Wjq23MoogHvEq6
    decimals: 9
    logoURI: /deployments/warp_routes/sSOL/logo.svg
    name: Solayer SOL
    standard: SealevelHypCollateral
    symbol: sSOL
  - addressOrDenom: XYbsJQGzZgPDbt9Swd2ao54nhGSq8Wjq23MoogHvEq6
    chainName: sonicsvm
    collateralAddressOrDenom: 21e27teReDgn7Z3J1ogdpJmFhUi75eYeiCD22zqCuwpd
    connections:
      - token: sealevel|solanamainnet|9PHKQFEDzedHuigSm1ZBojEX4DVF3cincGZwy3k7VHTN
    decimals: 9
    logoURI: /deployments/warp_routes/sSOL/logo.svg
    name: Solayer SOL
    standard: SealevelHypSynthetic
    symbol: sSOL
