tokens:
  - chainName: aleo
    standard: AleoHypSynthetic
    decimals: 9
    symbol: SOL
    name: Solana
    addressOrDenom: hyp_warp_token_sol.aleo/aleo1m3f6d2sp07ca6cpjw20xw7tv9qhvhu5t33ak6c830kjmxwl6s5zq5qswg8
    connections:
      - token: ethereum|hyperevm|0xEe3147deeDFC0c6DDD7c65D4e9ff9a48632BE645
  - chainName: hyperevm
    standard: EvmHypCollateral
    decimals: 9
    symbol: USOL
    name: Unit Solana
    addressOrDenom: "0xEe3147deeDFC0c6DDD7c65D4e9ff9a48632BE645"
    collateralAddressOrDenom: "0x068f321Fa8Fb9f0D135f290Ef6a3e2813e1c8A29"
    connections:
      - token: aleo|aleo|hyp_warp_token_sol.aleo/aleo1m3f6d2sp07ca6cpjw20xw7tv9qhvhu5t33ak6c830kjmxwl6s5zq5qswg8
