# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: GLpdg3jt6w4eVYiCMhokVZ4mX6hmRvPhcL5RoCjzGr5k
    chainName: eclipsemainnet
    collateralAddressOrDenom: 8SuhHnSEogAN2udZsoychjTafnaGgM9MCidYZEP8vuVY
    connections:
      - token: sealevel|solanamainnet|4UMNyNWW75zo69hxoJaRX5iXNUa5FdRPZZa9vDVCiESg
    decimals: 9
    logoURI: /deployments/warp_routes/SOL/logo.svg
    name: Solana
    standard: SealevelHypSynthetic
    symbol: SOL
  - addressOrDenom: 4UMNyNWW75zo69hxoJaRX5iXNUa5FdRPZZa9vDVCiESg
    chainName: solanamainnet
    collateralAddressOrDenom: ""
    connections:
      - token: sealevel|eclipsemainnet|GLpdg3jt6w4eVYiCMhokVZ4mX6hmRvPhcL5RoCjzGr5k
    decimals: 9
    logoURI: /deployments/warp_routes/SOL/logo.svg
    name: Solana
    standard: SealevelHypNative
    symbol: SOL
