# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x726f757465725f6170700000000000000000000000000001000000000000000c"
    chainName: celestia
    collateralAddressOrDenom: hyperlane/0x726f757465725f6170700000000000000000000000000002000000000000000a
    connections:
      - token: ethereum|eden|0x16eD50F96ea655Cb03638d7054e62e42Afb7b4fA
    decimals: 9
    name: SOL
    standard: CosmosNativeHypCollateral
    symbol: SOL
  - addressOrDenom: "0x16eD50F96ea655Cb03638d7054e62e42Afb7b4fA"
    chainName: eden
    connections:
      - token: cosmosnative|celestia|0x726f757465725f6170700000000000000000000000000001000000000000000c
    decimals: 9
    name: SOL
    standard: EvmHypSynthetic
    symbol: SOL
