# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x2A872Ae01375A5ca7e044cb0e75cb97621Ca954A"
    chainName: base
    coinGeckoId: coinbase-wrapped-btc
    collateralAddressOrDenom: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    connections:
      - token: ethereum|zeronetwork|0x3f7F02453518A55C0c6F89F0A6A8ab6c22Da01Df
    decimals: 8
    logoURI: /deployments/warp_routes/CBBTC/logo.svg
    name: Coinbase Wrapped BTC
    standard: EvmHypCollateral
    symbol: cbBTC
  - addressOrDenom: "0x3f7F02453518A55C0c6F89F0A6A8ab6c22Da01Df"
    chainName: zeronetwork
    connections:
      - token: ethereum|base|0x2A872Ae01375A5ca7e044cb0e75cb97621Ca954A
    decimals: 8
    logoURI: /deployments/warp_routes/CBBTC/logo.svg
    name: Coinbase Wrapped BTC
    standard: EvmHypSynthetic
    symbol: cbBTC
