# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: 4dLFhsXeK6QPxV2HEbXsF6eSTZdTFaGcGY5eEj5c8CbD
    chainName: eclipsemainnet
    collateralAddressOrDenom: HqDHrCWhdELCf21AAzhpAYTtKLtkqVzGfHTz7fo1yNxy
    connections:
      - token: sealevel|solanamainnet|21dbSbBdoEqUtJcvBkvhjpEiqb3LTrUFGQxKHWjY3WwV
      - token: sealevel|sonicsvm|5g9mjZ6TNJV7fH8eRbDgVZ344fGp43euUVNexv5Kawwo
      - token: sealevel|soon|A4UxZkWrEtfmhdtBE3VSS6n4E7Tnj7EMs5PA3hLgmFL8
    decimals: 9
    logoURI: /deployments/warp_routes/wfragJTO/logo.svg
    name: Wrapped Fragmetric Restaked JTO
    standard: SealevelHypSynthetic
    symbol: wfragJTO
  - addressOrDenom: 21dbSbBdoEqUtJcvBkvhjpEiqb3LTrUFGQxKHWjY3WwV
    chainName: solanamainnet
    coinGeckoId: wrapped-fragjto
    collateralAddressOrDenom: WFRGJnQt5pK8Dv4cDAbrSsgPcmboysrmX3RYhmRRyTR
    connections:
      - token: sealevel|eclipsemainnet|4dLFhsXeK6QPxV2HEbXsF6eSTZdTFaGcGY5eEj5c8CbD
      - token: sealevel|sonicsvm|5g9mjZ6TNJV7fH8eRbDgVZ344fGp43euUVNexv5Kawwo
      - token: sealevel|soon|A4UxZkWrEtfmhdtBE3VSS6n4E7Tnj7EMs5PA3hLgmFL8
    decimals: 9
    logoURI: /deployments/warp_routes/wfragJTO/logo.svg
    name: Wrapped Fragmetric Restaked JTO
    standard: SealevelHypCollateral
    symbol: wfragJTO
  - addressOrDenom: 5g9mjZ6TNJV7fH8eRbDgVZ344fGp43euUVNexv5Kawwo
    chainName: sonicsvm
    collateralAddressOrDenom: 4JbFLGRDNy9Ye6T7exs3bTBaBUrH2sWw88mRD2WhVTNr
    connections:
      - token: sealevel|eclipsemainnet|4dLFhsXeK6QPxV2HEbXsF6eSTZdTFaGcGY5eEj5c8CbD
      - token: sealevel|solanamainnet|21dbSbBdoEqUtJcvBkvhjpEiqb3LTrUFGQxKHWjY3WwV
      - token: sealevel|soon|A4UxZkWrEtfmhdtBE3VSS6n4E7Tnj7EMs5PA3hLgmFL8
    decimals: 9
    logoURI: /deployments/warp_routes/wfragJTO/logo.svg
    name: Wrapped Fragmetric Restaked JTO
    standard: SealevelHypSynthetic
    symbol: wfragJTO
  - addressOrDenom: A4UxZkWrEtfmhdtBE3VSS6n4E7Tnj7EMs5PA3hLgmFL8
    chainName: soon
    collateralAddressOrDenom: 6vrMyHTVQvmGzCjphMZxnfYV7R8C9tDWAQsWDTgCq1mE
    connections:
      - token: sealevel|eclipsemainnet|4dLFhsXeK6QPxV2HEbXsF6eSTZdTFaGcGY5eEj5c8CbD
      - token: sealevel|solanamainnet|21dbSbBdoEqUtJcvBkvhjpEiqb3LTrUFGQxKHWjY3WwV
      - token: sealevel|sonicsvm|5g9mjZ6TNJV7fH8eRbDgVZ344fGp43euUVNexv5Kawwo
    decimals: 9
    logoURI: /deployments/warp_routes/wfragJTO/logo.svg
    name: Wrapped Fragmetric Restaked JTO
    standard: SealevelHypSynthetic
    symbol: wfragJTO
