tokens:
  - chainName: aleo
    standard: AleoHypSynthetic
    decimals: 18
    symbol: USDT
    name: Tether USDC
    addressOrDenom: hyp_warp_token_usdt.aleo/aleo1t8xqj2q5lem2jr5gj6036am9hu69t59554cl5gd2pasxnjxmdsgsh98eqg
    connections:
      - token: ethereum|bsc|0x1FdA66FA15A261F01F1E09228D41bD0A806d7529
      - token: ethereum|ethereum|0x3C2064D78e4578E8F936E3db42aEF044E33FBF31
      - token: ethereum|hyperevm|0x36E437699E3658396Bf6229ddDaE54884cf28779
  - chainName: bsc
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x1FdA66FA15A261F01F1E09228D41bD0A806d7529"
    collateralAddressOrDenom: "0x55d398326f99059ff775485246999027b3197955"
    connections:
      - token: aleo|aleo|hyp_warp_token_usdt.aleo/aleo1t8xqj2q5lem2jr5gj6036am9hu69t59554cl5gd2pasxnjxmdsgsh98eqg
      - token: ethereum|ethereum|0x3C2064D78e4578E8F936E3db42aEF044E33FBF31
      - token: ethereum|hyperevm|0x36E437699E3658396Bf6229ddDaE54884cf28779
  - chainName: ethereum
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x3C2064D78e4578E8F936E3db42aEF044E33FBF31"
    collateralAddressOrDenom: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    connections:
      - token: aleo|aleo|hyp_warp_token_usdt.aleo/aleo1t8xqj2q5lem2jr5gj6036am9hu69t59554cl5gd2pasxnjxmdsgsh98eqg
      - token: ethereum|bsc|0x1FdA66FA15A261F01F1E09228D41bD0A806d7529
      - token: ethereum|hyperevm|0x36E437699E3658396Bf6229ddDaE54884cf28779
  - chainName: hyperevm
    standard: EvmHypCollateral
    decimals: 6
    symbol: USD₮0
    name: USD₮0
    addressOrDenom: "0x36E437699E3658396Bf6229ddDaE54884cf28779"
    collateralAddressOrDenom: "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb"
    connections:
      - token: aleo|aleo|hyp_warp_token_usdt.aleo/aleo1t8xqj2q5lem2jr5gj6036am9hu69t59554cl5gd2pasxnjxmdsgsh98eqg
      - token: ethereum|ethereum|0x3C2064D78e4578E8F936E3db42aEF044E33FBF31
      - token: ethereum|bsc|0x1FdA66FA15A261F01F1E09228D41bD0A806d7529
