# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e"
    chainName: arbitrum
    coinGeckoId: tether
    collateralAddressOrDenom: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    connections:
      - token: ethereum|mantle|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|mode|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|polygon|0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21
      - token: ethereum|scroll|0x0FC41a92F526A8CD22060A4052e156502D6B9db0
      - token: ethereum|zeronetwork|0x36dcfe3A0C6e0b5425F298587159249d780AAfab
      - token: ethereum|ethereum|0x95fBD1037a307A49587174E06a6600fD05c5f58e
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec"
    chainName: mantle
    coinGeckoId: tether
    collateralAddressOrDenom: "0x201EBa5CC46D216Ce6DC03F6a759e8E766e956aE"
    connections:
      - token: ethereum|arbitrum|0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e
      - token: ethereum|mode|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|polygon|0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21
      - token: ethereum|scroll|0x0FC41a92F526A8CD22060A4052e156502D6B9db0
      - token: ethereum|zeronetwork|0x36dcfe3A0C6e0b5425F298587159249d780AAfab
      - token: ethereum|ethereum|0x95fBD1037a307A49587174E06a6600fD05c5f58e
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec"
    chainName: mode
    coinGeckoId: tether
    collateralAddressOrDenom: "0xf0F161fDA2712DB8b566946122a5af183995e2eD"
    connections:
      - token: ethereum|arbitrum|0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e
      - token: ethereum|mantle|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|polygon|0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21
      - token: ethereum|scroll|0x0FC41a92F526A8CD22060A4052e156502D6B9db0
      - token: ethereum|zeronetwork|0x36dcfe3A0C6e0b5425F298587159249d780AAfab
      - token: ethereum|ethereum|0x95fBD1037a307A49587174E06a6600fD05c5f58e
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21"
    chainName: polygon
    coinGeckoId: tether
    collateralAddressOrDenom: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
    connections:
      - token: ethereum|arbitrum|0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e
      - token: ethereum|mantle|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|mode|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|scroll|0x0FC41a92F526A8CD22060A4052e156502D6B9db0
      - token: ethereum|zeronetwork|0x36dcfe3A0C6e0b5425F298587159249d780AAfab
      - token: ethereum|ethereum|0x95fBD1037a307A49587174E06a6600fD05c5f58e
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x0FC41a92F526A8CD22060A4052e156502D6B9db0"
    chainName: scroll
    coinGeckoId: tether
    collateralAddressOrDenom: "0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df"
    connections:
      - token: ethereum|arbitrum|0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e
      - token: ethereum|mantle|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|mode|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|polygon|0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21
      - token: ethereum|zeronetwork|0x36dcfe3A0C6e0b5425F298587159249d780AAfab
      - token: ethereum|ethereum|0x95fBD1037a307A49587174E06a6600fD05c5f58e
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x36dcfe3A0C6e0b5425F298587159249d780AAfab"
    chainName: zeronetwork
    connections:
      - token: ethereum|arbitrum|0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e
      - token: ethereum|mantle|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|mode|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|polygon|0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21
      - token: ethereum|scroll|0x0FC41a92F526A8CD22060A4052e156502D6B9db0
      - token: ethereum|ethereum|0x95fBD1037a307A49587174E06a6600fD05c5f58e
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypSynthetic
    symbol: USDT
  - addressOrDenom: "0x95fBD1037a307A49587174E06a6600fD05c5f58e"
    chainName: ethereum
    coinGeckoId: tether
    collateralAddressOrDenom: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    connections:
      - token: ethereum|arbitrum|0x83AF845F002c2dA8748eaB8203D2704BdAE6fB8e
      - token: ethereum|mantle|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|mode|0x803e7524526c579cCF6Ef0474d03012EdFD0d3Ec
      - token: ethereum|polygon|0x6701d503369cf6aA9e5EdFfEBFA40A2ffdf3dB21
      - token: ethereum|scroll|0x0FC41a92F526A8CD22060A4052e156502D6B9db0
      - token: ethereum|zeronetwork|0x36dcfe3A0C6e0b5425F298587159249d780AAfab
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
