# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4"
    chainName: arbitrum
    collateralAddressOrDenom: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    connections:
      - token: ethereum|base|0x3a669c00F7A041330646AC8AE89d74e104bd1363
      - token: ethereum|bsc|0xC05617bc2490CB57a8db163b5551bb7E532695e3
      - token: ethereum|eni|0x545E289B88c6d97b74eC0B96e308cae46Bf5f832
      - token: ethereum|ethereum|0x291A485Fd288786728Ba34052b95DDb60278AB49
      - token: ethereum|optimism|0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298
      - token: ethereum|polygon|0x98e9738DF4A304A97124D3A360A70DeC6efc4f99
    decimals: 6
    name: USDâ‚®0
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x3a669c00F7A041330646AC8AE89d74e104bd1363"
    chainName: base
    collateralAddressOrDenom: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
    connections:
      - token: ethereum|arbitrum|0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4
      - token: ethereum|bsc|0xC05617bc2490CB57a8db163b5551bb7E532695e3
      - token: ethereum|eni|0x545E289B88c6d97b74eC0B96e308cae46Bf5f832
      - token: ethereum|ethereum|0x291A485Fd288786728Ba34052b95DDb60278AB49
      - token: ethereum|optimism|0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298
      - token: ethereum|polygon|0x98e9738DF4A304A97124D3A360A70DeC6efc4f99
    decimals: 6
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0xC05617bc2490CB57a8db163b5551bb7E532695e3"
    chainName: bsc
    collateralAddressOrDenom: "0x55d398326f99059fF775485246999027B3197955"
    connections:
      - token: ethereum|arbitrum|0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4
      - token: ethereum|base|0x3a669c00F7A041330646AC8AE89d74e104bd1363
      - token: ethereum|eni|0x545E289B88c6d97b74eC0B96e308cae46Bf5f832
      - token: ethereum|ethereum|0x291A485Fd288786728Ba34052b95DDb60278AB49
      - token: ethereum|optimism|0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298
      - token: ethereum|polygon|0x98e9738DF4A304A97124D3A360A70DeC6efc4f99
    decimals: 18
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x545E289B88c6d97b74eC0B96e308cae46Bf5f832"
    chainName: eni
    connections:
      - token: ethereum|arbitrum|0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4
      - token: ethereum|base|0x3a669c00F7A041330646AC8AE89d74e104bd1363
      - token: ethereum|bsc|0xC05617bc2490CB57a8db163b5551bb7E532695e3
      - token: ethereum|ethereum|0x291A485Fd288786728Ba34052b95DDb60278AB49
      - token: ethereum|optimism|0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298
      - token: ethereum|polygon|0x98e9738DF4A304A97124D3A360A70DeC6efc4f99
    decimals: 6
    name: Tether USD
    standard: EvmHypSynthetic
    symbol: USDT
  - addressOrDenom: "0x291A485Fd288786728Ba34052b95DDb60278AB49"
    chainName: ethereum
    collateralAddressOrDenom: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    connections:
      - token: ethereum|arbitrum|0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4
      - token: ethereum|base|0x3a669c00F7A041330646AC8AE89d74e104bd1363
      - token: ethereum|bsc|0xC05617bc2490CB57a8db163b5551bb7E532695e3
      - token: ethereum|eni|0x545E289B88c6d97b74eC0B96e308cae46Bf5f832
      - token: ethereum|optimism|0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298
      - token: ethereum|polygon|0x98e9738DF4A304A97124D3A360A70DeC6efc4f99
    decimals: 6
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298"
    chainName: optimism
    collateralAddressOrDenom: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58"
    connections:
      - token: ethereum|arbitrum|0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4
      - token: ethereum|base|0x3a669c00F7A041330646AC8AE89d74e104bd1363
      - token: ethereum|bsc|0xC05617bc2490CB57a8db163b5551bb7E532695e3
      - token: ethereum|eni|0x545E289B88c6d97b74eC0B96e308cae46Bf5f832
      - token: ethereum|ethereum|0x291A485Fd288786728Ba34052b95DDb60278AB49
      - token: ethereum|polygon|0x98e9738DF4A304A97124D3A360A70DeC6efc4f99
    decimals: 6
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x98e9738DF4A304A97124D3A360A70DeC6efc4f99"
    chainName: polygon
    collateralAddressOrDenom: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
    connections:
      - token: ethereum|arbitrum|0x92637DCE7F34b9e9b5741B9203F33EED7f71E5a4
      - token: ethereum|base|0x3a669c00F7A041330646AC8AE89d74e104bd1363
      - token: ethereum|bsc|0xC05617bc2490CB57a8db163b5551bb7E532695e3
      - token: ethereum|eni|0x545E289B88c6d97b74eC0B96e308cae46Bf5f832
      - token: ethereum|ethereum|0x291A485Fd288786728Ba34052b95DDb60278AB49
      - token: ethereum|optimism|0x2EbFeC15f3Ff64E52af17c1c9a4aE9B7f6574298
    decimals: 6
    name: USDT0
    standard: EvmHypCollateral
    symbol: USDT
