# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x4221a16A01F61c2b38A03C52d828a7041f6AAA49"
    chainName: ethereum
    coinGeckoId: tether
    collateralAddressOrDenom: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    connections:
      - token: ethereum|viction|0x48083c69f5a42c6b69abbad48ae195bd36770ee2
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: USDT
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x48083c69f5a42c6b69abbad48ae195bd36770ee2"
    chainName: viction
    connections:
      - token: ethereum|ethereum|0x4221a16A01F61c2b38A03C52d828a7041f6AAA49
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: USDT
    standard: EvmHypSynthetic
    symbol: USDT
