# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xab852e67bf03E74C89aF67C4BA97dd1088D3dA19"
    chainName: ethereum
    collateralAddressOrDenom: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    connections:
      - token: ethereum|inevm|0x97423a68bae94b5de52d767a17abcc54c157c0e5
    decimals: 6
    name: USDT
    standard: EvmHypCollateral
    symbol: USDT
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDT/logo.svg
  - addressOrDenom: "0x97423a68bae94b5de52d767a17abcc54c157c0e5"
    chainName: inevm
    connections:
      - token: ethereum|ethereum|0xab852e67bf03E74C89aF67C4BA97dd1088D3dA19
    decimals: 6
    name: USDT
    standard: EvmHypSynthetic
    symbol: USDT
    logoURI: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/deployments/warp_routes/USDT/logo.svg
