# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xE78fA49bE021e533cd8f6E10931b796D89cd80DD"
    chainName: ethereum
    coinGeckoId: tether
    collateralAddressOrDenom: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    connections:
      - token: ethereum|krown|0x59973ae98D340cA0577ed92502402E82E987Ba2E
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x59973ae98D340cA0577ed92502402E82E987Ba2E"
    chainName: krown
    connections:
      - token: ethereum|ethereum|0xE78fA49bE021e533cd8f6E10931b796D89cd80DD
    decimals: 6
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypSynthetic
    symbol: USDT
