tokens:
  - addressOrDenom: "0xa0e73E30945B80010503E68e53AbFd0B6B6a6ed9"
    chainName: bsc
    coinGeckoId: tether
    collateralAddressOrDenom: "0x55d398326f99059fF775485246999027B3197955"
    connections:
      - token: ethereum|matchain|0xa0e73E30945B80010503E68e53AbFd0B6B6a6ed9
    decimals: 18
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0xa0e73E30945B80010503E68e53AbFd0B6B6a6ed9"
    chainName: matchain
    connections:
      - token: ethereum|bsc|0xa0e73E30945B80010503E68e53AbFd0B6B6a6ed9
    decimals: 18
    logoURI: /deployments/warp_routes/USDT/logo.svg
    name: Tether USD
    standard: EvmHypSynthetic
    symbol: USDT
