tokens:
  - chainName: arbitrum
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x6BEC839292A36372882Cb850E93FB5aC2A9BA4Af"
    collateralAddressOrDenom: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    connections: []
  - chainName: base
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x23c51024b19303F1315DbFFA055666aE9B7A0B2c"
    collateralAddressOrDenom: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
    connections: []
