# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: 2JvSu7PzquY2b8NDZbnupFZ1jezqMBtNUhi7TuU3GQJD
    chainName: eclipsemainnet
    collateralAddressOrDenom: GnBAskb2SQjrLgpTjtgatz4hEugUsYV7XrWU1idV3oqW
    connections:
      - token: ethereum|ethereum|0x3eE1BEA3A10f7508b76219f109eBe19419b3dd85
      - token: sealevel|solanamainnet|9Cu9VqDPPzntFZMar4gCdw6EGL3RbofLEqyh6WKSZKGm
    decimals: 6
    logoURI: /deployments/warp_routes/ES/logo.svg
    name: Eclipse
    standard: SealevelHypSynthetic
    symbol: ES
  - addressOrDenom: "0x3eE1BEA3A10f7508b76219f109eBe19419b3dd85"
    chainName: ethereum
    coinGeckoId: eclipse-3
    collateralAddressOrDenom: "0x6055Dc6Ff1077eebe5e6D2BA1a1f53d7Ef8430dE"
    connections:
      - token: sealevel|eclipsemainnet|2JvSu7PzquY2b8NDZbnupFZ1jezqMBtNUhi7TuU3GQJD
      - token: sealevel|solanamainnet|9Cu9VqDPPzntFZMar4gCdw6EGL3RbofLEqyh6WKSZKGm
    decimals: 6
    logoURI: /deployments/warp_routes/ES/logo.svg
    name: Eclipse
    standard: EvmHypCollateral
    symbol: ES
  - addressOrDenom: 9Cu9VqDPPzntFZMar4gCdw6EGL3RbofLEqyh6WKSZKGm
    chainName: solanamainnet
    collateralAddressOrDenom: BqPqrrQuoQXFGGEAEMnPmDgZ6RWQCajWnY3V6Yp4DZWP
    connections:
      - token: ethereum|ethereum|0x3eE1BEA3A10f7508b76219f109eBe19419b3dd85
      - token: sealevel|eclipsemainnet|2JvSu7PzquY2b8NDZbnupFZ1jezqMBtNUhi7TuU3GQJD
    decimals: 6
    logoURI: /deployments/warp_routes/ES/logo.svg
    name: Eclipse
    standard: SealevelHypSynthetic
    symbol: ES
