tokens:
  - chainName: soneium
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: USDSC
    name: Startale USD
    addressOrDenom: "0x867D428B8FbE196EA4e997e7980623E75ED219a7"
    collateralAddressOrDenom: "0x3f99231dD03a9F0E7e3421c92B7b90fbe012985a"
    connections: []
