# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x7b4Bf9fEcCfF207eF2CB7101Ceb15b8516021AcD"
    chainName: bsc
    connections:
      - token: cosmosnative|milkyway|0x726f757465725f61707000000000000000000000000000010000000000000000
    decimals: 6
    logoURI: /deployments/warp_routes/MILK/logo.svg
    name: MilkyWay
    standard: EvmHypSynthetic
    symbol: MILK
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000000"
    chainName: milkyway
    coinGeckoId: milkyway-2
    connections:
      - token: ethereum|bsc|0x7b4Bf9fEcCfF207eF2CB7101Ceb15b8516021AcD
    decimals: 6
    logoURI: /deployments/warp_routes/MILK/logo.svg
    name: MilkyWay
    standard: CosmosNativeHypCollateral
    symbol: MILK
