# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x9E2946d1C41082D32d1fDffA723e6cA2d4364Ad3"
    chainName: sepolia
    decimals: 6
    name: Aleo Testnet
    standard: EvmHypSynthetic
    symbol: ALEO
  - addressOrDenom: "test_hyp_warp_token_credits.aleo/aleo1e394kmnr0f3j4anxvqnqe57tmv06kp7v7uyyu598gk9wn7d7w58qq9h2qz"
    chainName: aleotestnet
    decimals: 6
    name: Aleo Testnet
    standard: AleoHypNative
    symbol: ALEO
