# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xcbfb6dBeb6C06DdCd345781a0ADc711A86a77f7c"
    chainName: abstract
    connections:
      - token: ethereum|ethereum|0x53ccE6d10e43d1B3D11872Ad22eC2aCd8d2537B8
      - token: sealevel|solanamainnet|7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
    decimals: 18
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: EvmHypSynthetic
    symbol: SMOL
  - addressOrDenom: "0x32AD8eEb9831afe4B8f19FCF7B318c6526B8B781"
    chainName: arbitrum
    coinGeckoId: smolcoin
    collateralAddressOrDenom: "0x9E64D3b9e8eC387a9a58CED80b71Ed815f8D82B5"
    connections:
      - token: ethereum|abstract|0xcbfb6dBeb6C06DdCd345781a0ADc711A86a77f7c
      - token: ethereum|ethereum|0x53ccE6d10e43d1B3D11872Ad22eC2aCd8d2537B8
      - token: sealevel|solanamainnet|7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
    decimals: 18
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: EvmHypCollateral
    symbol: SMOL
  - addressOrDenom: "0x53ccE6d10e43d1B3D11872Ad22eC2aCd8d2537B8"
    chainName: ethereum
    connections:
      - token: ethereum|abstract|0xcbfb6dBeb6C06DdCd345781a0ADc711A86a77f7c
      - token: sealevel|solanamainnet|7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
    decimals: 18
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: EvmHypSynthetic
    symbol: SMOL
  - addressOrDenom: 7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
    chainName: solanamainnet
    collateralAddressOrDenom: 5KHQeeQvM4qBtmX3WnaCMGpM3Th7jYpqcHf3c6qzPodM
    connections:
      - token: ethereum|abstract|0xcbfb6dBeb6C06DdCd345781a0ADc711A86a77f7c
      - token: ethereum|ethereum|0x53ccE6d10e43d1B3D11872Ad22eC2aCd8d2537B8
    decimals: 9
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: SealevelHypSynthetic
    symbol: SMOL
