# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: BSrwJNiHM88XRYX93CRXGSTR4GfnZfxn3kTa4rvanPKr
    chainName: solanamainnet
    coinGeckoId: popcat
    collateralAddressOrDenom: 7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr
    connections:
      - token: sealevel|soon|2CPGmQCNdGrh45n6BgTG98G7AkQfEKPZCcYW2reju2kn
    decimals: 9
    logoURI: /deployments/warp_routes/POPCAT/logo.svg
    name: POPCAT
    standard: SealevelHypCollateral
    symbol: POPCAT
  - addressOrDenom: 2CPGmQCNdGrh45n6BgTG98G7AkQfEKPZCcYW2reju2kn
    chainName: soon
    collateralAddressOrDenom: Hxf93wyFCRi4Je5R1dYc4xAtPug48YdC6vuorUJFW5dv
    connections:
      - token: sealevel|solanamainnet|BSrwJNiHM88XRYX93CRXGSTR4GfnZfxn3kTa4rvanPKr
    decimals: 9
    logoURI: /deployments/warp_routes/POPCAT/logo.svg
    name: POPCAT
    standard: SealevelHypSynthetic
    symbol: POPCAT
