tokens:
  - addressOrDenom: "0xd5985Ba1C2873e5F5b83F49D7EBE2cB50F1c25fA"
    chainName: bsc
    coinGeckoId: binance-peg-weth
    collateralAddressOrDenom: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8"
    connections:
      - token: ethereum|carrchain|0xE514c211C44A7752542Addc1650be244FA626d22
      - token: ethereum|ethereum|0x25b0F02B26cB369Fefa6EFc3F8e8eDB5371C55BC
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ethereum Token
    standard: EvmHypCollateral
    symbol: ETH
  - addressOrDenom: "0xE514c211C44A7752542Addc1650be244FA626d22"
    chainName: carrchain
    connections:
      - token: ethereum|bsc|0xd5985Ba1C2873e5F5b83F49D7EBE2cB50F1c25fA
      - token: ethereum|ethereum|0x25b0F02B26cB369Fefa6EFc3F8e8eDB5371C55BC
    decimals: 18
    logoURI: /deployments/warp_routes/WETH/logo.svg
    name: Wrapped Ether
    standard: EvmHypSynthetic
    symbol: WETH
  - addressOrDenom: "0x25b0F02B26cB369Fefa6EFc3F8e8eDB5371C55BC"
    chainName: ethereum
    coinGeckoId: weth
    collateralAddressOrDenom: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    connections:
      - token: ethereum|bsc|0xd5985Ba1C2873e5F5b83F49D7EBE2cB50F1c25fA
      - token: ethereum|carrchain|0xE514c211C44A7752542Addc1650be244FA626d22
    decimals: 18
    logoURI: /deployments/warp_routes/WETH/logo.svg
    name: Wrapped Ether
    standard: EvmHypCollateral
    symbol: WETH
