tokens:
  - chainName: linea
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: mUSD
    name: MetaMask USD
    addressOrDenom: "0xb9Fc2748D7f4d81cfc2ca78a52f52b4ADf1C4895"
    collateralAddressOrDenom: "0xaca92e438df0b2401ff60da7e4337b687a2435da"
    connections: []
