# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4"
    chainName: arbitrum
    collateralAddressOrDenom: "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"
    connections:
      - token: ethereum|bsc|0xD42Af909d323D88e0E933B6c50D3e91c279004ca
      - token: ethereum|kalychain|0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455
      - token: ethereum|polygon|0xfF00e814A0dCB9a614585c212C78Fdc596d02e47
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
  - addressOrDenom: "0xD42Af909d323D88e0E933B6c50D3e91c279004ca"
    chainName: bsc
    collateralAddressOrDenom: "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c"
    connections:
      - token: ethereum|arbitrum|0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4
      - token: ethereum|kalychain|0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455
      - token: ethereum|polygon|0xfF00e814A0dCB9a614585c212C78Fdc596d02e47
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
  - addressOrDenom: "0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4
      - token: ethereum|bsc|0xD42Af909d323D88e0E933B6c50D3e91c279004ca
      - token: ethereum|polygon|0xfF00e814A0dCB9a614585c212C78Fdc596d02e47
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypSynthetic
    symbol: WBTC
  - addressOrDenom: "0xfF00e814A0dCB9a614585c212C78Fdc596d02e47"
    chainName: polygon
    collateralAddressOrDenom: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
    connections:
      - token: ethereum|arbitrum|0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4
      - token: ethereum|bsc|0xD42Af909d323D88e0E933B6c50D3e91c279004ca
      - token: ethereum|kalychain|0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
