# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xd59be1Da2e9B30b6f7aB27b2D08f841B39c349fa"
    chainName: eni
    connections:
      - token: ethereum|ethereum|0x52FcCFD806f11c0eB61912A24Ca09547626739e7
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypSynthetic
    symbol: WBTC
  - addressOrDenom: "0x52FcCFD806f11c0eB61912A24Ca09547626739e7"
    chainName: ethereum
    collateralAddressOrDenom: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
    connections:
      - token: ethereum|eni|0xd59be1Da2e9B30b6f7aB27b2D08f841B39c349fa
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
