# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x745C75868237F3635c486fe166639Cc4706512A9"
    chainName: ethereum
    coinGeckoId: wrapped-bitcoin
    collateralAddressOrDenom: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
    connections:
      - token: ethereum|mode|0x3c38fC01159E7BE0685653A0C896eA49F2BAa7c1
      - token: ethereum|scroll|0x10a5263ACED246fCD0977f1a3C6A238a14183096
      - token: ethereum|zeronetwork|0xe6ca7C4A9652Fe93190Bd84363f2056Df1fb9A94
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
  - addressOrDenom: "0x3c38fC01159E7BE0685653A0C896eA49F2BAa7c1"
    chainName: mode
    coinGeckoId: wrapped-bitcoin
    collateralAddressOrDenom: "0xcDd475325D6F564d27247D1DddBb0DAc6fA0a5CF"
    connections:
      - token: ethereum|ethereum|0x745C75868237F3635c486fe166639Cc4706512A9
      - token: ethereum|scroll|0x10a5263ACED246fCD0977f1a3C6A238a14183096
      - token: ethereum|zeronetwork|0xe6ca7C4A9652Fe93190Bd84363f2056Df1fb9A94
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
  - addressOrDenom: "0x10a5263ACED246fCD0977f1a3C6A238a14183096"
    chainName: scroll
    coinGeckoId: wrapped-bitcoin
    collateralAddressOrDenom: "0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1"
    connections:
      - token: ethereum|ethereum|0x745C75868237F3635c486fe166639Cc4706512A9
      - token: ethereum|mode|0x3c38fC01159E7BE0685653A0C896eA49F2BAa7c1
      - token: ethereum|zeronetwork|0xe6ca7C4A9652Fe93190Bd84363f2056Df1fb9A94
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
  - addressOrDenom: "0xe6ca7C4A9652Fe93190Bd84363f2056Df1fb9A94"
    chainName: zeronetwork
    connections:
      - token: ethereum|ethereum|0x745C75868237F3635c486fe166639Cc4706512A9
      - token: ethereum|mode|0x3c38fC01159E7BE0685653A0C896eA49F2BAa7c1
      - token: ethereum|scroll|0x10a5263ACED246fCD0977f1a3C6A238a14183096
    decimals: 8
    logoURI: /deployments/warp_routes/WBTC/logo.svg
    name: Wrapped BTC
    standard: EvmHypSynthetic
    symbol: WBTC
