# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000006"
    chainName: celestiatestnet
    collateralAddressOrDenom: utia
    connections:
      - token: ethereum|edentestnet|0xcC79A8081D8cFd3da61dE7a25Bc06CCe00BbDa54
    decimals: 6
    logoURI: /deployments/warp_routes/TIA/logo.svg
    name: TIA
    standard: CosmosNativeHypCollateral
    symbol: TIA
  - addressOrDenom: "0xcC79A8081D8cFd3da61dE7a25Bc06CCe00BbDa54"
    chainName: edentestnet
    connections:
      - token: cosmosnative|celestiatestnet|0x726f757465725f61707000000000000000000000000000010000000000000006
    decimals: 6
    logoURI: /deployments/warp_routes/TIA/logo.svg
    name: TIA
    standard: EvmHypSynthetic
    symbol: TIA
