# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xDB190f6A84Ae202E7e5248F398F989Fc817cc2Bc"
    chainName: hyperevm
    collateralAddressOrDenom: "0x111111a1a0667d36bd57c0a9f569b98057111111"
    decimals: 6
    name: USDH
    standard: EvmHypMultiCollateral
    symbol: USDH
