tokens:
  - chainName: hyperevm
    standard: EvmHypCollateralAdapter
    decimals: 6
    symbol: USDH
    name: USD Hyperliquid
    addressOrDenom: "0xc7d07C8acFC66852BAad9Afb49E8A3AA7F6D3575"
    collateralAddressOrDenom: "0x111111a1a0667d36bd57c0a9f569b98057111111"
    connections: []
