# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xEa35E107fB64Ff8C3c8c37DB2d23A7179f31D8EC"
    chainName: ethereum
    collateralAddressOrDenom: "0xE7deE4823EE18F1347F1Cf7997f70B94eFDe2E1F"
    connections:
      - token: ethereum|form|0x688da80Dfe2916c0a0Aa360323E52Aa5881AdB78
    decimals: 18
    logoURI: /deployments/warp_routes/FORM/logo.svg
    name: Form
    standard: EvmHypCollateral
    symbol: FORM
  - addressOrDenom: "0x688da80Dfe2916c0a0Aa360323E52Aa5881AdB78"
    chainName: form
    connections:
      - token: ethereum|ethereum|0xEa35E107fB64Ff8C3c8c37DB2d23A7179f31D8EC
    decimals: 18
    logoURI: /deployments/warp_routes/FORM/logo.svg
    name: Form
    standard: EvmHypSynthetic
    symbol: FORM
