tokens:
  - addressOrDenom: hyp_warp_token_usad.aleo/aleo19n3zsqu9f9g6r7j0n2relyv3uvhyzsa5mla6p0jl528z6dhums9ss07msp
    chainName: aleo
    decimals: 6
    name: USAD
    standard: AleoHypSynthetic
    symbol: USAD
  - addressOrDenom: "0x52E96C79DC3a1813577DBfB411B92E8C96Cb3d91"
    chainName: ethereum
    collateralAddressOrDenom: "0xC60a7e21A6753ED4305C93034607009fAeC2A5F3"
    decimals: 6
    name: USAD
    standard: EvmHypCollateral
    symbol: USAD
