tokens:
  - addressOrDenom: test_hyp_warp_token_usad.aleo/aleo1c9kdv4xgnww0rhk8hth8s8c9cl8w7ja9shpwdupsug26m9kaayqq6segar
    chainName: aleotestnet
    connections:
      - token: ethereum|sepolia|0xf95A2e563972E200F6239f60bB0eefCf62F00E63
    decimals: 6
    logoURI: /deployments/warp_routes/USAD/logo.svg
    name: USAD
    standard: AleoHypSynthetic
    symbol: USAD
  - addressOrDenom: "0xf95A2e563972E200F6239f60bB0eefCf62F00E63"
    chainName: sepolia
    collateralAddressOrDenom: "0xC60a7e21A6753ED4305C93034607009fAeC2A5F3"
    connections:
      - token: aleo|aleotestnet|test_hyp_warp_token_usad.aleo/aleo1c9kdv4xgnww0rhk8hth8s8c9cl8w7ja9shpwdupsug26m9kaayqq6segar
    decimals: 6
    logoURI: /deployments/warp_routes/USAD/logo.svg
    name: USAD
    standard: EvmHypCollateral
    symbol: USAD
