# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xb475C9a3d52340e37a5007cA43a2f0D4876A4b74"
    chainName: berachain
    collateralAddressOrDenom: "0xDe9e4211087A43112b0e0e9d840459Acf1d9E6C8"
    connections:
      - token: ethereum|ethereum|0xFF5C5b61AE627D6659a70aD72A76f1bE7343fEEC
      - token: ethereum|swell|0xCBC928268870F216A510c207C456544660ec8566
      - token: ethereum|unichain|0xd5C36a45e3B7fCeFf0d926dc377d4648a8301cc4
      - token: ethereum|zircuit|0x5891A7EDB2734C3dAAE7a9FF66cdf98b46aF02F6
    decimals: 18
    name: Renzo Restaked LST Stage
    standard: EvmHypXERC20
    symbol: PZETHSTAGE
  - addressOrDenom: "0xFF5C5b61AE627D6659a70aD72A76f1bE7343fEEC"
    chainName: ethereum
    collateralAddressOrDenom: "0x9E1a2b6de93164b77Fc5CA11e647EECB38BB463D"
    connections:
      - token: ethereum|berachain|0xb475C9a3d52340e37a5007cA43a2f0D4876A4b74
      - token: ethereum|swell|0xCBC928268870F216A510c207C456544660ec8566
      - token: ethereum|unichain|0xd5C36a45e3B7fCeFf0d926dc377d4648a8301cc4
      - token: ethereum|zircuit|0x5891A7EDB2734C3dAAE7a9FF66cdf98b46aF02F6
    decimals: 18
    name: Renzo Restaked LST Stage
    standard: EvmHypXERC20Lockbox
    symbol: PZETHSTAGE
  - addressOrDenom: "0xCBC928268870F216A510c207C456544660ec8566"
    chainName: swell
    collateralAddressOrDenom: "0xDe9e4211087A43112b0e0e9d840459Acf1d9E6C8"
    connections:
      - token: ethereum|berachain|0xb475C9a3d52340e37a5007cA43a2f0D4876A4b74
      - token: ethereum|ethereum|0xFF5C5b61AE627D6659a70aD72A76f1bE7343fEEC
      - token: ethereum|unichain|0xd5C36a45e3B7fCeFf0d926dc377d4648a8301cc4
      - token: ethereum|zircuit|0x5891A7EDB2734C3dAAE7a9FF66cdf98b46aF02F6
    decimals: 18
    name: Renzo Restaked LST Stage
    standard: EvmHypXERC20
    symbol: PZETHSTAGE
  - addressOrDenom: "0xd5C36a45e3B7fCeFf0d926dc377d4648a8301cc4"
    chainName: unichain
    collateralAddressOrDenom: "0xDe9e4211087A43112b0e0e9d840459Acf1d9E6C8"
    connections:
      - token: ethereum|berachain|0xb475C9a3d52340e37a5007cA43a2f0D4876A4b74
      - token: ethereum|ethereum|0xFF5C5b61AE627D6659a70aD72A76f1bE7343fEEC
      - token: ethereum|swell|0xCBC928268870F216A510c207C456544660ec8566
      - token: ethereum|zircuit|0x5891A7EDB2734C3dAAE7a9FF66cdf98b46aF02F6
    decimals: 18
    name: Renzo Restaked LST Stage
    standard: EvmHypXERC20
    symbol: PZETHSTAGE
  - addressOrDenom: "0x5891A7EDB2734C3dAAE7a9FF66cdf98b46aF02F6"
    chainName: zircuit
    collateralAddressOrDenom: "0xDe9e4211087A43112b0e0e9d840459Acf1d9E6C8"
    connections:
      - token: ethereum|berachain|0xb475C9a3d52340e37a5007cA43a2f0D4876A4b74
      - token: ethereum|ethereum|0xFF5C5b61AE627D6659a70aD72A76f1bE7343fEEC
      - token: ethereum|swell|0xCBC928268870F216A510c207C456544660ec8566
      - token: ethereum|unichain|0xd5C36a45e3B7fCeFf0d926dc377d4648a8301cc4
    decimals: 18
    name: Renzo Restaked LST Stage
    standard: EvmHypXERC20
    symbol: PZETHSTAGE
