tokens:
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000011"
    chainName: celestia
    collateralAddressOrDenom: hyperlane/0x726f757465725f6170700000000000000000000000000002000000000000000e
    connections:
      - token: ethereum|eden|0xFA3198ecF05303a6d96E57a45E6c815055D255b1
    decimals: 8
    logoURI: /deployments/warp_routes/BTC/logo.svg
    name: BTC
    standard: CosmosNativeHypCollateral
    symbol: BTC
  - addressOrDenom: "0xFA3198ecF05303a6d96E57a45E6c815055D255b1"
    chainName: eden
    connections:
      - token: cosmosnative|celestia|0x726f757465725f61707000000000000000000000000000010000000000000011
    decimals: 8
    logoURI: /deployments/warp_routes/BTC/logo.svg
    name: BTC
    standard: EvmHypSynthetic
    symbol: BTC
