# yaml-language-server: $schema=../schema.json
tokens:
  # M0 wM on BSC (SpokePortal)
  - addressOrDenom: "0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE"
    chainName: bsc
    collateralAddressOrDenom: "0x437cc33344a0B27A429f795ff6B469C72698B291"
    connections:
      - token: ethereum|ethereum|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
      - token: ethereum|linea|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
    decimals: 6
    logoURI: /deployments/warp_routes/wM/logo.png
    name: WrappedM by M^0
    standard: EvmM0PortalLite
    symbol: wM
  # M0 wM on Ethereum (HubPortal)
  - addressOrDenom: "0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE"
    chainName: ethereum
    collateralAddressOrDenom: "0x437cc33344a0B27A429f795ff6B469C72698B291"
    connections:
      - token: ethereum|bsc|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
      - token: ethereum|soneium|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
    decimals: 6
    logoURI: /deployments/warp_routes/wM/logo.png
    name: WrappedM by M^0
    standard: EvmM0PortalLite
    symbol: wM
  # M0 wM on Linea (SpokePortal)
  - addressOrDenom: "0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE"
    chainName: linea
    collateralAddressOrDenom: "0x437cc33344a0B27A429f795ff6B469C72698B291"
    connections:
      - token: ethereum|bsc|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
    decimals: 6
    logoURI: /deployments/warp_routes/wM/logo.png
    name: WrappedM by M^0
    standard: EvmM0PortalLite
    symbol: wM
  # M0 wM on Soneium (SpokePortal)
  - addressOrDenom: "0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE"
    chainName: soneium
    collateralAddressOrDenom: "0x437cc33344a0B27A429f795ff6B469C72698B291"
    connections:
      - token: ethereum|ethereum|0x36f586A30502AE3afb555b8aA4dCc05d233c2ecE
    decimals: 6
    logoURI: /deployments/warp_routes/wM/logo.png
    name: WrappedM by M^0
    standard: EvmM0PortalLite
    symbol: wM
