# Hyperlane core deployment for Cypherium
# Generated manually from deployment logs
mailbox: "0x17fcEf595646FB1eB94d93B62EE256a2C2a7f337"
interchainAccountRouter: "0x74c058367ee8A1F748952b6F973BFA9De5bF89A1"
validatorAnnounce: "0x1eD8634917b1EB02a24e7b1fd630fc6E4121DD2e"
merkleTreeHook: "0x73404aD208d4079f709723B415BE612BF3550372"
proxyAdmin: "0xf9F5244ce3Abaf084EE53682f2D76649f98BfD72"
testRecipient: "0x8dE66b90A215a746B1d8504f3b8d6B809Fd5432A"

# Factories
staticMerkleRootMultisigIsmFactory: "0xD258adC28084379A75631E0ea55034F4c606f958"
staticMessageIdMultisigIsmFactory: "0xbd2c55254E31BF78356d7C9AbbC0a37383770AD4"
staticAggregationIsmFactory: "0xfb1BE491cddca74f5f980939AC2D3F26b17b7207"
staticAggregationHookFactory: "0x0E420B044d1250C45fFefe9e2D364Fdc060257ba"
domainRoutingIsmFactory: "0x54245a5cFCBE6519b6991844cd3F48e4456AA35C"
staticMerkleRootWeightedMultisigIsmFactory: "0xb687c45411a9e58A2e0b6de9dAC49A7abdc221FA"
staticMessageIdWeightedMultisigIsmFactory: "0x2bDEe87C0c9C5B4F5957e00D954D8AF0252dAa38"

# Optional protocolFee (from logs)
protocolFee: "0x8b7f8b24d559170c8ce8163927e28b215dd67e02e5f17b10a975140c19704001"
