tokens:
  - chainName: arbitrum
    standard: EvmHypSyntheticWithMinters
    decimals: 6
    symbol: sUSD
    name: StableSwap USD
    addressOrDenom: "0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6"
    connections:
      - token: ethereum|base|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|soneium|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|mantra|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|linea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|hyperevm|0x0a089A151228Fd8CdfB1082a12b030D4C064F497
  - chainName: base
    standard: EvmHypSyntheticWithMinters
    decimals: 6
    symbol: sUSD
    name: StableSwap USD
    addressOrDenom: "0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6"
    connections:
      - token: ethereum|arbitrum|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|soneium|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|mantra|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|linea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|hyperevm|0x0a089A151228Fd8CdfB1082a12b030D4C064F497
  - chainName: soneium
    standard: EvmHypSyntheticWithMinters
    decimals: 6
    symbol: sUSD
    name: StableSwap USD
    addressOrDenom: "0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6"
    connections:
      - token: ethereum|arbitrum|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|base|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|mantra|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|linea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|hyperevm|0x0a089A151228Fd8CdfB1082a12b030D4C064F497
  - chainName: mantra
    standard: EvmHypSyntheticWithMinters
    decimals: 6
    symbol: sUSD
    name: StableSwap USD
    addressOrDenom: "0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6"
    connections:
      - token: ethereum|arbitrum|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|base|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|soneium|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|linea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|hyperevm|0x0a089A151228Fd8CdfB1082a12b030D4C064F497
  - chainName: linea
    standard: EvmHypSyntheticWithMinters
    decimals: 6
    symbol: sUSD
    name: StableSwap USD
    addressOrDenom: "0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6"
    connections:
      - token: ethereum|arbitrum|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|base|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|soneium|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|mantra|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|hyperevm|0x0a089A151228Fd8CdfB1082a12b030D4C064F497
  - chainName: hyperevm
    standard: EvmHypSyntheticWithMinters
    decimals: 6
    symbol: sUSD
    name: StableSwap USD
    addressOrDenom: "0x0a089A151228Fd8CdfB1082a12b030D4C064F497"
    connections:
      - token: ethereum|arbitrum|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|base|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|soneium|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|mantra|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
      - token: ethereum|linea|0x38E8720EBE02e7c5254F9De9F81440C7a770a9c6
