name: check-warp-deploy
on:
  # Triggers the workflow on pull request events
  pull_request:
jobs:
  check-warp-deploy:
    permissions:
      # require PR write perms to be able to comment on the PR
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.HYPER_GONK_APP_ID }}
          private-key: ${{ secrets.HYPER_GONK_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Determine Base & Head SHA
        id: determine-base-sha
        run: |
          echo "base_sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          echo "current_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Check Warp Deploy
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          ./scripts/check-warp-deploy.sh ${{ steps.determine-base-sha.outputs.base_sha }} ${{ steps.determine-base-sha.outputs.current_sha }}
