name: ci

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [main]
  pull_request:
  # For queues into main
  merge_group:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: build
        run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: lint
        run: pnpm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: prettier
        run: |
          pnpm run prettier
          CHANGES=$(git status -s)
          if [[ ! -z $CHANGES ]]; then
            echo "Changes found: $CHANGES"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: test
        run: pnpm run test:unit

      - name: validate-file-path
        run: |
          node ./scripts/validate-file-path.js

      - name: validate-svg
        run: |
          node ./scripts/validate-svg.js

      - name: validate-file-data
        run: |
          node ./scripts/validate-file-data.js

  changeset:
    if: ${{ github.event_name == 'pull_request' && github.head_ref != 'changeset-release/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # check out full history
          fetch-depth: 0
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: changeset
        run: pnpm exec changeset status --since origin/main
