name: combine

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.HYPER_GONK_APP_ID }}
          private-key: ${{ secrets.HYPER_GONK_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || 'main' }}
          # Use Hyper Gonk token to allow CI to trigger on commits pushed by this workflow
          token: ${{ steps.generate-token.outputs.token }}

      - name: yarn-install
        uses: ./.github/actions/yarn-install-with-cache

      - name: foundry-install
        uses: foundry-rs/foundry-toolchain@v1

      - name: combine-data
        run: |
          echo "Assembling warp route configs, chain metadata and addresses together..."
          yarn build

      - name: commit-changes
        uses: ./.github/actions/commit-changes
        with:
          message: "Update chain metadata and address files"

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: optimize-svgs
        run: |
          node ./scripts/optimize-svg.js

      - name: commit-changes
        uses: ./.github/actions/commit-changes
        with:
          message: "Optimize SVG files"
