name: combine

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.HYPER_GONK_APP_ID }}
          private-key: ${{ secrets.HYPER_GONK_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || 'main' }}
          # Use Hyper Gonk token to allow CI to trigger on commits pushed by this workflow
          token: ${{ steps.generate-token.outputs.token }}

      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache

      - name: foundry-install
        uses: foundry-rs/foundry-toolchain@v1

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api /users/${{ steps.generate-token.outputs.app-slug }}[bot] --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Configure Git for Hyper Gonk
        run: |
          git config user.name "${{ steps.generate-token.outputs.app-slug }}[bot]"
          git config user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com"

      - name: combine-data
        run: |
          echo "Assembling warp route configs, chain metadata and addresses together..."
          pnpm build

      - name: commit-changes
        uses: ./.github/actions/commit-changes
        with:
          message: "Update chain metadata and address files"

      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: optimize-svgs
        run: |
          node ./scripts/optimize-svg.js

      - name: commit-changes
        uses: ./.github/actions/commit-changes
        with:
          message: "Optimize SVG files"
