name: rpc-healthcheck

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  rpc-health-mainnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: test
        run: pnpm run test:rpc-health-mainnet

  rpc-health-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: pnpm-cache
        uses: ./.github/actions/pnpm-cache
      - name: test
        run: pnpm run test:rpc-health-testnet
